import type {
  IndexQuote,
  BondYield,
  Commodity,
  HeatmapSector,
  EconomicIndicator,
  MacroSnapshot,
  BlogPost,
} from "@/types";

export const EQUITY_INDICES: IndexQuote[] = [
  {
    symbol: "^GSPC",
    name: "S&P 500",
    region: "USA",
    flag: "🇺🇸",
    value: 5842.3,
    weekChange: 1.24,
    monthChange: 2.81,
    ytdChange: 8.42,
    dailyChange: 0.38,
    sparkline: [5320, 5380, 5290, 5410, 5460, 5510, 5490, 5580, 5620, 5700, 5780, 5842],
  },
  {
    symbol: "^NDX",
    name: "NASDAQ 100",
    region: "USA",
    flag: "🇺🇸",
    value: 21084.6,
    weekChange: 1.87,
    monthChange: 3.94,
    ytdChange: 11.23,
    dailyChange: 0.62,
    sparkline: [18900, 19100, 18750, 19300, 19600, 20000, 19800, 20200, 20500, 20700, 20900, 21084],
  },
  {
    symbol: "000001.SS",
    name: "Shanghai Composite",
    region: "China",
    flag: "🇨🇳",
    value: 3412.7,
    weekChange: -0.84,
    monthChange: 1.12,
    ytdChange: 3.21,
    dailyChange: -0.31,
    sparkline: [3180, 3220, 3190, 3250, 3310, 3290, 3350, 3380, 3420, 3400, 3440, 3412],
  },
  {
    symbol: "^N225",
    name: "Nikkei 225",
    region: "Japan",
    flag: "🇯🇵",
    value: 39284.5,
    weekChange: 0.42,
    monthChange: -1.18,
    ytdChange: 5.67,
    dailyChange: 0.15,
    sparkline: [37200, 37800, 37400, 38100, 38500, 38200, 38900, 39100, 38800, 39200, 39100, 39284],
  },
  {
    symbol: "^NSEI",
    name: "NIFTY 50",
    region: "India",
    flag: "🇮🇳",
    value: 25142.8,
    weekChange: 2.14,
    monthChange: 4.32,
    ytdChange: 9.84,
    dailyChange: 0.78,
    sparkline: [22800, 23100, 23000, 23400, 23800, 24100, 24000, 24400, 24700, 25000, 24900, 25142],
  },
  {
    symbol: "^GDAXI",
    name: "DAX",
    region: "Germany",
    flag: "🇩🇪",
    value: 22318.4,
    weekChange: 1.56,
    monthChange: 3.21,
    ytdChange: 12.44,
    dailyChange: 0.44,
    sparkline: [19800, 20200, 20000, 20500, 20900, 21200, 21000, 21400, 21700, 22000, 22100, 22318],
  },
  {
    symbol: "^FTSE",
    name: "FTSE 100",
    region: "UK",
    flag: "🇬🇧",
    value: 8823.9,
    weekChange: 0.91,
    monthChange: 1.87,
    ytdChange: 6.23,
    dailyChange: 0.22,
    sparkline: [8200, 8300, 8250, 8380, 8450, 8490, 8510, 8580, 8620, 8700, 8760, 8823],
  },
  {
    symbol: "^FCHI",
    name: "CAC 40",
    region: "France",
    flag: "🇫🇷",
    value: 8241.6,
    weekChange: 1.12,
    monthChange: 2.44,
    ytdChange: 7.89,
    dailyChange: 0.31,
    sparkline: [7600, 7700, 7650, 7800, 7900, 8000, 7950, 8050, 8100, 8150, 8200, 8241],
  },
  {
    symbol: "^GSPTSE",
    name: "S&P/TSX Composite",
    region: "Canada",
    flag: "🇨🇦",
    value: 25684.2,
    weekChange: 0.68,
    monthChange: 1.44,
    ytdChange: 4.12,
    dailyChange: 0.19,
    sparkline: [24200, 24500, 24300, 24700, 24900, 25100, 25000, 25200, 25300, 25500, 25600, 25684],
  },
  {
    symbol: "^KS11",
    name: "KOSPI",
    region: "South Korea",
    flag: "🇰🇷",
    value: 2748.3,
    weekChange: -0.34,
    monthChange: 0.82,
    ytdChange: 2.18,
    dailyChange: -0.12,
    sparkline: [2620, 2660, 2640, 2690, 2720, 2700, 2730, 2760, 2750, 2770, 2760, 2748],
  },
];

export const BOND_YIELDS: BondYield[] = [
  {
    country: "United States",
    flag: "🇺🇸",
    maturity: "10Y",
    yield: 4.38,
    dailyMove: 0.03,
    oneMonthMove: -0.12,
    oneYearMove: 0.21,
    trend: [4.82, 4.71, 4.65, 4.48, 4.32, 4.41, 4.28, 4.35, 4.22, 4.31, 4.35, 4.38],
  },
  {
    country: "Canada",
    flag: "🇨🇦",
    maturity: "10Y",
    yield: 3.84,
    dailyMove: 0.02,
    oneMonthMove: -0.08,
    oneYearMove: 0.14,
    trend: [4.21, 4.12, 4.05, 3.98, 3.88, 3.92, 3.82, 3.88, 3.78, 3.82, 3.82, 3.84],
  },
  {
    country: "Germany",
    flag: "🇩🇪",
    maturity: "10Y",
    yield: 2.68,
    dailyMove: 0.01,
    oneMonthMove: -0.15,
    oneYearMove: -0.22,
    trend: [2.98, 2.91, 2.85, 2.78, 2.65, 2.72, 2.58, 2.65, 2.55, 2.62, 2.65, 2.68],
  },
  {
    country: "India",
    flag: "🇮🇳",
    maturity: "10Y",
    yield: 6.92,
    dailyMove: -0.02,
    oneMonthMove: -0.18,
    oneYearMove: -0.34,
    trend: [7.48, 7.38, 7.28, 7.18, 7.05, 7.12, 6.98, 7.05, 6.88, 6.95, 6.90, 6.92],
  },
  {
    country: "China",
    flag: "🇨🇳",
    maturity: "10Y",
    yield: 2.24,
    dailyMove: -0.01,
    oneMonthMove: -0.08,
    oneYearMove: -0.48,
    trend: [2.78, 2.71, 2.65, 2.55, 2.42, 2.38, 2.32, 2.28, 2.22, 2.25, 2.22, 2.24],
  },
  {
    country: "Japan",
    flag: "🇯🇵",
    maturity: "10Y",
    yield: 1.52,
    dailyMove: 0.02,
    oneMonthMove: 0.14,
    oneYearMove: 0.82,
    trend: [0.72, 0.88, 0.95, 1.02, 1.08, 1.12, 1.18, 1.25, 1.32, 1.38, 1.45, 1.52],
  },
  {
    country: "South Korea",
    flag: "🇰🇷",
    maturity: "10Y",
    yield: 3.12,
    dailyMove: 0.01,
    oneMonthMove: -0.06,
    oneYearMove: -0.28,
    trend: [3.58, 3.48, 3.42, 3.35, 3.25, 3.28, 3.18, 3.22, 3.12, 3.15, 3.12, 3.12],
  },
];

export const COMMODITIES: Commodity[] = [
  {
    symbol: "BZ=F",
    name: "Brent Crude",
    unit: "USD/bbl",
    value: 74.82,
    dailyChange: -0.84,
    weekChange: -2.14,
    monthChange: -4.32,
    ytdChange: -8.21,
    icon: "🛢️",
  },
  {
    symbol: "CL=F",
    name: "WTI Crude",
    unit: "USD/bbl",
    value: 71.34,
    dailyChange: -0.92,
    weekChange: -2.38,
    monthChange: -4.88,
    ytdChange: -9.14,
    icon: "⛽",
  },
  {
    symbol: "GC=F",
    name: "Gold",
    unit: "USD/oz",
    value: 3312.40,
    dailyChange: 0.62,
    weekChange: 1.84,
    monthChange: 3.42,
    ytdChange: 12.84,
    icon: "🟡",
  },
  {
    symbol: "HG=F",
    name: "Copper",
    unit: "USD/lb",
    value: 4.84,
    dailyChange: 0.28,
    weekChange: 0.84,
    monthChange: 2.18,
    ytdChange: 6.42,
    icon: "🟠",
  },
  {
    symbol: "NG=F",
    name: "Natural Gas",
    unit: "USD/MMBtu",
    value: 3.24,
    dailyChange: 1.24,
    weekChange: 3.14,
    monthChange: -1.84,
    ytdChange: 14.28,
    icon: "🔥",
  },
];

export const HEATMAP_DATA: HeatmapSector[] = [
  {
    name: "Technology",
    value: 31.2,
    change: 1.84,
    children: [
      { name: "NVDA", ticker: "NVDA", value: 6.8, change: 3.42 },
      { name: "AAPL", ticker: "AAPL", value: 6.2, change: 0.82 },
      { name: "MSFT", ticker: "MSFT", value: 5.8, change: 1.24 },
      { name: "META", ticker: "META", value: 3.4, change: 2.18 },
      { name: "AVGO", ticker: "AVGO", value: 2.8, change: 2.84 },
      { name: "AMD", ticker: "AMD", value: 2.1, change: 4.12 },
      { name: "ORCL", ticker: "ORCL", value: 1.8, change: 1.44 },
      { name: "ADBE", ticker: "ADBE", value: 1.4, change: -0.82 },
      { name: "INTC", ticker: "INTC", value: 0.9, change: -1.24 },
    ],
  },
  {
    name: "Financials",
    value: 13.4,
    change: 0.42,
    children: [
      { name: "BRK.B", ticker: "BRK.B", value: 3.2, change: 0.28 },
      { name: "JPM", ticker: "JPM", value: 2.8, change: 0.64 },
      { name: "V", ticker: "V", value: 2.4, change: 0.88 },
      { name: "MA", ticker: "MA", value: 2.0, change: 0.72 },
      { name: "BAC", ticker: "BAC", value: 1.6, change: -0.34 },
      { name: "GS", ticker: "GS", value: 1.4, change: 1.12 },
    ],
  },
  {
    name: "Healthcare",
    value: 11.8,
    change: -0.28,
    children: [
      { name: "LLY", ticker: "LLY", value: 3.4, change: 0.84 },
      { name: "UNH", ticker: "UNH", value: 2.8, change: -2.14 },
      { name: "JNJ", ticker: "JNJ", value: 2.2, change: -0.42 },
      { name: "ABBV", ticker: "ABBV", value: 1.8, change: 0.62 },
      { name: "MRK", ticker: "MRK", value: 1.6, change: -0.88 },
    ],
  },
  {
    name: "Consumer Disc.",
    value: 10.2,
    change: 1.14,
    children: [
      { name: "AMZN", ticker: "AMZN", value: 4.8, change: 1.84 },
      { name: "TSLA", ticker: "TSLA", value: 2.2, change: 2.44 },
      { name: "HD", ticker: "HD", value: 1.8, change: 0.42 },
      { name: "NKE", ticker: "NKE", value: 1.4, change: -1.24 },
    ],
  },
  {
    name: "Communication",
    value: 8.8,
    change: 2.24,
    children: [
      { name: "GOOGL", ticker: "GOOGL", value: 4.2, change: 2.84 },
      { name: "NFLX", ticker: "NFLX", value: 2.4, change: 1.84 },
      { name: "DIS", ticker: "DIS", value: 1.2, change: 0.84 },
      { name: "T", ticker: "T", value: 1.0, change: 2.14 },
    ],
  },
  {
    name: "Industrials",
    value: 8.4,
    change: 0.18,
    children: [
      { name: "CAT", ticker: "CAT", value: 2.2, change: 0.44 },
      { name: "RTX", ticker: "RTX", value: 1.8, change: 0.82 },
      { name: "HON", ticker: "HON", value: 1.6, change: -0.28 },
      { name: "UPS", ticker: "UPS", value: 1.4, change: -0.84 },
      { name: "GE", ticker: "GE", value: 1.4, change: 0.64 },
    ],
  },
  {
    name: "Energy",
    value: 3.8,
    change: -1.24,
    children: [
      { name: "XOM", ticker: "XOM", value: 1.8, change: -1.44 },
      { name: "CVX", ticker: "CVX", value: 1.2, change: -1.08 },
      { name: "COP", ticker: "COP", value: 0.8, change: -1.18 },
    ],
  },
  {
    name: "Consumer Staples",
    value: 5.8,
    change: 0.08,
    children: [
      { name: "PG", ticker: "PG", value: 2.2, change: 0.24 },
      { name: "KO", ticker: "KO", value: 1.6, change: -0.14 },
      { name: "PEP", ticker: "PEP", value: 1.4, change: 0.08 },
      { name: "WMT", ticker: "WMT", value: 0.6, change: 0.44 },
    ],
  },
  {
    name: "Materials",
    value: 2.4,
    change: 0.84,
    children: [
      { name: "LIN", ticker: "LIN", value: 1.2, change: 0.88 },
      { name: "FCX", ticker: "FCX", value: 0.8, change: 1.44 },
      { name: "NEM", ticker: "NEM", value: 0.4, change: -0.24 },
    ],
  },
  {
    name: "Utilities",
    value: 2.2,
    change: -0.14,
    children: [
      { name: "NEE", ticker: "NEE", value: 1.2, change: -0.24 },
      { name: "SO", ticker: "SO", value: 1.0, change: -0.04 },
    ],
  },
  {
    name: "Real Estate",
    value: 2.0,
    change: 0.22,
    children: [
      { name: "PLD", ticker: "PLD", value: 1.0, change: 0.44 },
      { name: "AMT", ticker: "AMT", value: 1.0, change: 0.0 },
    ],
  },
];

// Generate time series for economic indicators
function genTimeSeries(
  base: number,
  periods: number,
  trend: number,
  volatility: number,
  dateFormat: "monthly" | "quarterly" = "monthly"
): { date: string; value: number }[] {
  const series: { date: string; value: number }[] = [];
  let val = base;
  const now = new Date(2026, 4, 1); // May 2026
  for (let i = periods - 1; i >= 0; i--) {
    const d = new Date(now);
    if (dateFormat === "quarterly") {
      d.setMonth(d.getMonth() - i * 3);
    } else {
      d.setMonth(d.getMonth() - i);
    }
    const noise = (Math.random() - 0.5) * volatility;
    val = val + trend / periods + noise;
    series.push({
      date: d.toISOString().slice(0, 7),
      value: parseFloat(val.toFixed(2)),
    });
  }
  return series;
}

export const ECONOMIC_INDICATORS: EconomicIndicator[] = [
  {
    id: "us-gdp",
    name: "US GDP Growth",
    category: "growth",
    country: "United States",
    flag: "🇺🇸",
    value: 2.4,
    unit: "% QoQ",
    previousValue: 2.1,
    change: 0.3,
    direction: "up",
    isPositiveGood: true,
    period: "Q1 2026",
    description: "US economy expanding at a solid pace, driven by resilient consumer spending and AI investment.",
    timeSeries: genTimeSeries(1.8, 16, 0.6, 0.4, "quarterly"),
  },
  {
    id: "china-gdp",
    name: "China GDP Growth",
    category: "growth",
    country: "China",
    flag: "🇨🇳",
    value: 4.8,
    unit: "% YoY",
    previousValue: 5.1,
    change: -0.3,
    direction: "down",
    isPositiveGood: true,
    period: "Q1 2026",
    description: "China's growth slowing amid property sector headwinds, though exports remain a bright spot.",
    timeSeries: genTimeSeries(5.2, 16, -0.4, 0.3, "quarterly"),
  },
  {
    id: "us-jobless-claims",
    name: "US Initial Jobless Claims",
    category: "employment",
    country: "United States",
    flag: "🇺🇸",
    value: 218,
    unit: "K",
    previousValue: 224,
    change: -6,
    direction: "down",
    isPositiveGood: false,
    period: "Week of May 24",
    description: "Initial claims declining, signaling continued labour market resilience.",
    timeSeries: genTimeSeries(235, 24, -17, 8),
  },
  {
    id: "us-unemployment",
    name: "US Unemployment Rate",
    category: "employment",
    country: "United States",
    flag: "🇺🇸",
    value: 3.9,
    unit: "%",
    previousValue: 4.1,
    change: -0.2,
    direction: "down",
    isPositiveGood: false,
    period: "Apr 2026",
    description: "Unemployment edging lower, reflecting steady hiring in services and technology sectors.",
    timeSeries: genTimeSeries(4.2, 24, -0.3, 0.1),
  },
  {
    id: "china-mfg-pmi",
    name: "China Manufacturing PMI",
    category: "manufacturing",
    country: "China",
    flag: "🇨🇳",
    value: 50.4,
    unit: "Index",
    previousValue: 49.8,
    change: 0.6,
    direction: "up",
    isPositiveGood: true,
    period: "Apr 2026",
    description: "Manufacturing activity back above the 50-point expansion threshold, led by new export orders.",
    timeSeries: genTimeSeries(48.8, 24, 1.6, 0.8),
  },
  {
    id: "india-services-pmi",
    name: "India Services PMI",
    category: "services",
    country: "India",
    flag: "🇮🇳",
    value: 58.8,
    unit: "Index",
    previousValue: 57.4,
    change: 1.4,
    direction: "up",
    isPositiveGood: true,
    period: "Apr 2026",
    description: "India's services sector surging to near-record levels, underpinned by domestic demand and IT exports.",
    timeSeries: genTimeSeries(53.2, 24, 5.6, 1.2),
  },
  {
    id: "us-cpi",
    name: "US CPI Inflation",
    category: "inflation",
    country: "United States",
    flag: "🇺🇸",
    value: 2.8,
    unit: "% YoY",
    previousValue: 3.1,
    change: -0.3,
    direction: "down",
    isPositiveGood: false,
    period: "Apr 2026",
    description: "Inflation continues its gradual descent toward the Fed's 2% target, driven by easing shelter costs.",
    timeSeries: genTimeSeries(3.8, 24, -1.0, 0.2),
  },
  {
    id: "korea-exports",
    name: "South Korea Exports",
    category: "trade",
    country: "South Korea",
    flag: "🇰🇷",
    value: 578.4,
    unit: "USD B",
    previousValue: 554.2,
    change: 4.4,
    direction: "up",
    isPositiveGood: true,
    period: "Apr 2026",
    description: "Korean exports expanding on strong global demand for semiconductors and electric vehicles.",
    timeSeries: genTimeSeries(510, 24, 68, 18),
  },
  {
    id: "china-exports",
    name: "China Exports",
    category: "trade",
    country: "China",
    flag: "🇨🇳",
    value: 8.4,
    unit: "% YoY",
    previousValue: 6.2,
    change: 2.2,
    direction: "up",
    isPositiveGood: true,
    period: "Apr 2026",
    description: "China's export growth accelerating as manufacturers redirect supply chains to emerging markets.",
    timeSeries: genTimeSeries(4.2, 24, 4.2, 2.0),
  },
  {
    id: "brent-oil",
    name: "Brent Crude Oil",
    category: "energy",
    country: "Global",
    flag: "🌍",
    value: 74.82,
    unit: "USD/bbl",
    previousValue: 76.44,
    change: -2.12,
    direction: "down",
    isPositiveGood: false,
    period: "May 2026",
    description: "Brent crude declining on demand growth concerns, partially offset by OPEC+ production discipline.",
    timeSeries: genTimeSeries(88, 24, -13.18, 4),
  },
  {
    id: "baltic-dry",
    name: "Baltic Dry Index",
    category: "shipping",
    country: "Global",
    flag: "🌊",
    value: 1284,
    unit: "Index",
    previousValue: 1342,
    change: -4.3,
    direction: "down",
    isPositiveGood: true,
    period: "May 2026",
    description: "Baltic Dry Index softening as dry bulk shipping demand eases with moderating Chinese commodity imports.",
    timeSeries: genTimeSeries(1850, 24, -566, 180),
  },
  {
    id: "drewry-wci",
    name: "Drewry World Container Index",
    category: "shipping",
    country: "Global",
    flag: "📦",
    value: 2184,
    unit: "USD/FEU",
    previousValue: 2312,
    change: -5.5,
    direction: "down",
    isPositiveGood: false,
    period: "May 2026",
    description: "Container rates easing from elevated levels as Red Sea disruptions normalize and capacity returns.",
    timeSeries: genTimeSeries(3200, 24, -1016, 280),
  },
];

export const MACRO_SNAPSHOT: MacroSnapshot = {
  gdp: { value: 2.4, trend: "up" },
  pmi: { value: 50.4, trend: "up" },
  inflation: { value: 2.8, trend: "down" },
  exports: { value: 8.4, trend: "up" },
  shipping: { value: 1284, trend: "down" },
  oil: { value: 74.82, trend: "down" },
};

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "fed-pivot-2026",
    title: "The Fed's Calculated Pause: What Rate Markets Are Pricing In",
    excerpt:
      "With CPI trending toward target and the labour market showing resilience, the Fed finds itself in a rare moment of patience. Here's what the yield curve is telling us about the path ahead.",
    date: "2026-05-28",
    category: "Monetary Policy",
    readTime: 7,
    tags: ["Federal Reserve", "Interest Rates", "Inflation"],
  },
  {
    slug: "china-exports-acceleration",
    title: "China's Export Engine Reignites — But Who's Buying?",
    excerpt:
      "April's export data beat consensus by a wide margin. The surprise isn't the volume — it's the destination. Emerging markets are absorbing what the West once did.",
    date: "2026-05-24",
    category: "Global Trade",
    readTime: 5,
    tags: ["China", "Exports", "Emerging Markets"],
  },
  {
    slug: "india-services-record",
    title: "India's Services PMI at Near-Record: The Decade-Long Thesis Playing Out",
    excerpt:
      "India's services PMI hit 58.8 in April — near the highest reading in a decade. This isn't a blip. It's the structural shift that patient investors have been waiting for.",
    date: "2026-05-20",
    category: "Emerging Markets",
    readTime: 6,
    tags: ["India", "PMI", "Services"],
  },
  {
    slug: "shipping-rates-normalization",
    title: "The Great Container Rate Unwind: What It Means for Inflation",
    excerpt:
      "After two years of elevated freight rates, the Drewry WCI is normalizing. This is the disinflationary tailwind that nobody in the CPI models is giving enough credit to.",
    date: "2026-05-15",
    category: "Shipping & Trade",
    readTime: 4,
    tags: ["Shipping", "Inflation", "Supply Chain"],
  },
];
