// Ticker → full company name lookup for heatmap tooltips
export const TICKER_NAMES: Record<string, string> = {
  // ── S&P 500 ───────────────────────────────────────────────────────────────
  // Technology
  NVDA: "NVIDIA Corp.",
  AAPL: "Apple Inc.",
  MSFT: "Microsoft Corp.",
  AVGO: "Broadcom Inc.",
  ORCL: "Oracle Corp.",
  CRM: "Salesforce Inc.",
  AMD: "Advanced Micro Devices",
  ADBE: "Adobe Inc.",
  CSCO: "Cisco Systems",
  ACN: "Accenture plc",
  INTC: "Intel Corp.",
  TXN: "Texas Instruments",
  QCOM: "Qualcomm Inc.",
  IBM: "IBM Corp.",
  NOW: "ServiceNow Inc.",
  INTU: "Intuit Inc.",
  AMAT: "Applied Materials",
  MU: "Micron Technology",
  ADI: "Analog Devices",
  LRCX: "Lam Research",
  // Communication
  GOOGL: "Alphabet Inc. (Class A)",
  GOOG: "Alphabet Inc. (Class C)",
  META: "Meta Platforms",
  NFLX: "Netflix Inc.",
  DIS: "Walt Disney Co.",
  TMUS: "T-Mobile US",
  CMCSA: "Comcast Corp.",
  T: "AT&T Inc.",
  VZ: "Verizon Communications",
  // Consumer Discretionary
  AMZN: "Amazon.com Inc.",
  TSLA: "Tesla Inc.",
  HD: "Home Depot",
  MCD: "McDonald's Corp.",
  NKE: "Nike Inc.",
  LOW: "Lowe's Companies",
  SBUX: "Starbucks Corp.",
  BKNG: "Booking Holdings",
  TJX: "TJX Companies",
  ORLY: "O'Reilly Automotive",
  // Financials
  "BRK.B": "Berkshire Hathaway",
  JPM: "JPMorgan Chase",
  V: "Visa Inc.",
  MA: "Mastercard Inc.",
  BAC: "Bank of America",
  WFC: "Wells Fargo",
  GS: "Goldman Sachs",
  MS: "Morgan Stanley",
  AXP: "American Express",
  SPGI: "S&P Global",
  BLK: "BlackRock Inc.",
  C: "Citigroup Inc.",
  SCHW: "Charles Schwab",
  // Healthcare
  LLY: "Eli Lilly & Co.",
  UNH: "UnitedHealth Group",
  JNJ: "Johnson & Johnson",
  MRK: "Merck & Co.",
  ABBV: "AbbVie Inc.",
  TMO: "Thermo Fisher Scientific",
  ABT: "Abbott Laboratories",
  PFE: "Pfizer Inc.",
  DHR: "Danaher Corp.",
  AMGN: "Amgen Inc.",
  ISRG: "Intuitive Surgical",
  CVS: "CVS Health",
  BMY: "Bristol-Myers Squibb",
  // Industrials
  GE: "General Electric",
  CAT: "Caterpillar Inc.",
  RTX: "RTX Corp.",
  HON: "Honeywell International",
  UNP: "Union Pacific",
  BA: "Boeing Co.",
  LMT: "Lockheed Martin",
  DE: "Deere & Co.",
  UPS: "United Parcel Service",
  ETN: "Eaton Corp.",
  ADP: "Automatic Data Processing",
  // Consumer Staples
  WMT: "Walmart Inc.",
  PG: "Procter & Gamble",
  COST: "Costco Wholesale",
  KO: "Coca-Cola Co.",
  PEP: "PepsiCo Inc.",
  PM: "Philip Morris International",
  MDLZ: "Mondelez International",
  CL: "Colgate-Palmolive",
  // Energy
  XOM: "ExxonMobil Corp.",
  CVX: "Chevron Corp.",
  COP: "ConocoPhillips",
  SLB: "Schlumberger NV",
  EOG: "EOG Resources",
  // Utilities
  NEE: "NextEra Energy",
  SO: "Southern Co.",
  DUK: "Duke Energy",
  CEG: "Constellation Energy",
  // Materials
  LIN: "Linde plc",
  SHW: "Sherwin-Williams",
  FCX: "Freeport-McMoRan",
  NEM: "Newmont Corp.",
  // Real Estate
  PLD: "Prologis Inc.",
  AMT: "American Tower",
  EQIX: "Equinix Inc.",
  WELL: "Welltower Inc.",

  // ── S&P/TSX ───────────────────────────────────────────────────────────────
  // Financials
  RY: "Royal Bank of Canada",
  TD: "TD Bank",
  BMO: "Bank of Montreal",
  BNS: "Bank of Nova Scotia (Scotiabank)",
  CM: "CIBC",
  BN: "Brookfield Corp.",
  MFC: "Manulife Financial",
  SLF: "Sun Life Financial",
  NA: "National Bank of Canada",
  IFC: "Intact Financial",
  FFH: "Fairfax Financial Holdings",
  GWO: "Great-West Lifeco",
  POW: "Power Corp. of Canada",
  // Energy
  ENB: "Enbridge Inc.",
  CNQ: "Canadian Natural Resources",
  SU: "Suncor Energy",
  TRP: "TC Energy",
  CVE: "Cenovus Energy",
  IMO: "Imperial Oil",
  TOU: "Tourmaline Oil",
  PPL: "Pembina Pipeline",
  ARX: "ARC Resources",
  // Materials
  AEM: "Agnico Eagle Mines",
  WPM: "Wheaton Precious Metals",
  NTR: "Nutrien Ltd.",
  ABX: "Barrick Gold",
  FNV: "Franco-Nevada Corp.",
  TECK: "Teck Resources",
  FM: "First Quantum Minerals",
  NGT: "Newmont Goldcorp (TSX)",
  K: "Kinross Gold",
  // Industrials
  CP: "Canadian Pacific Kansas City",
  CNR: "Canadian National Railway",
  WCN: "Waste Connections",
  "GIB.A": "CGI Inc.",
  TFII: "TFI International",
  TIH: "Toromont Industries",
  // Technology
  SHOP: "Shopify Inc.",
  CSU: "Constellation Software",
  OTEX: "Open Text Corp.",
  DSG: "Descartes Systems",
  // Consumer
  ATD: "Alimentation Couche-Tard",
  QSR: "Restaurant Brands International",
  DOL: "Dollarama Inc.",
  L: "Loblaw Companies",
  WN: "George Weston Ltd.",
  MRU: "Metro Inc.",
  // Telecom
  BCE: "BCE Inc.",
  "RCI.B": "Rogers Communications",
  // Utilities
  FTS: "Fortis Inc.",
  H: "Hydro One",
  EMA: "Emera Inc.",
  AQN: "Algonquin Power & Utilities",
  // Real Estate
  "CAR.UN": "Canadian Apartment Properties REIT",
  "REI.UN": "RioCan REIT",

  // ── NIFTY 50 ──────────────────────────────────────────────────────────────
  // Financials
  HDFCBANK: "HDFC Bank",
  ICICIBANK: "ICICI Bank",
  KOTAKBANK: "Kotak Mahindra Bank",
  SBIN: "State Bank of India",
  AXISBANK: "Axis Bank",
  BAJFINANCE: "Bajaj Finance",
  BAJAJFINSV: "Bajaj Finserv",
  INDUSINDBK: "IndusInd Bank",
  SBILIFE: "SBI Life Insurance",
  HDFCLIFE: "HDFC Life Insurance",
  // IT
  INFY: "Infosys Ltd.",
  TCS: "Tata Consultancy Services",
  HCLTECH: "HCL Technologies",
  WIPRO: "Wipro Ltd.",
  TECHM: "Tech Mahindra",
  LTIM: "LTIMindtree",
  // Energy
  RELIANCE: "Reliance Industries",
  NTPC: "NTPC Ltd.",
  ONGC: "Oil & Natural Gas Corp.",
  POWERGRID: "Power Grid Corp. of India",
  COALINDIA: "Coal India Ltd.",
  BPCL: "Bharat Petroleum",
  // Consumer
  ITC: "ITC Ltd.",
  HINDUNILVR: "Hindustan Unilever",
  TITAN: "Titan Co.",
  ASIANPAINT: "Asian Paints",
  NESTLEIND: "Nestle India",
  TATACONSUM: "Tata Consumer Products",
  BRITANNIA: "Britannia Industries",
  // Auto
  TATAMOTORS: "Tata Motors",
  MARUTI: "Maruti Suzuki India",
  "M&M": "Mahindra & Mahindra",
  "BAJAJ-AUTO": "Bajaj Auto",
  EICHERMOT: "Eicher Motors",
  HEROMOTOCO: "Hero MotoCorp",
  // Materials
  ULTRACEMCO: "UltraTech Cement",
  TATASTEEL: "Tata Steel",
  JSWSTEEL: "JSW Steel",
  HINDALCO: "Hindalco Industries",
  GRASIM: "Grasim Industries",
  UPL: "UPL Ltd.",
  // Pharma
  SUNPHARMA: "Sun Pharmaceutical",
  DRREDDY: "Dr. Reddy's Laboratories",
  CIPLA: "Cipla Ltd.",
  DIVISLAB: "Divi's Laboratories",
  APOLLOHOSP: "Apollo Hospitals",
  // Industrials
  LT: "Larsen & Toubro",
  ADANIPORTS: "Adani Ports & SEZ",
  ADANIENT: "Adani Enterprises",
  // Telecom
  BHARTIARTL: "Bharti Airtel",

  // ── NASDAQ 100 (names not already in S&P 500) ────────────────────────────
  KLAC: "KLA Corp.",
  MRVL: "Marvell Technology",
  NXPI: "NXP Semiconductors",
  MCHP: "Microchip Technology",
  FTNT: "Fortinet Inc.",
  CDNS: "Cadence Design Systems",
  SNPS: "Synopsys Inc.",
  CRWD: "CrowdStrike Holdings",
  PANW: "Palo Alto Networks",
  ASML: "ASML Holding NV",
  PYPL: "PayPal Holdings",
  TEAM: "Atlassian Corp.",
  DDOG: "Datadog Inc.",
  WDAY: "Workday Inc.",
  ADSK: "Autodesk Inc.",
  ANSS: "Ansys Inc.",
  CHTR: "Charter Communications",
  ROKU: "Roku Inc.",
  MAR: "Marriott International",
  ABNB: "Airbnb Inc.",
  MELI: "MercadoLibre Inc.",
  ROST: "Ross Stores",
  LULU: "Lululemon Athletica",
  EBAY: "eBay Inc.",
  GILD: "Gilead Sciences",
  REGN: "Regeneron Pharmaceuticals",
  VRTX: "Vertex Pharmaceuticals",
  IDXX: "IDEXX Laboratories",
  ILMN: "Illumina Inc.",
  DXCM: "Dexcom Inc.",
  MRNA: "Moderna Inc.",
  ZTS: "Zoetis Inc.",
  MNST: "Monster Beverage",
  KDP: "Keurig Dr Pepper",
  KHC: "Kraft Heinz Co.",
  PAYX: "Paychex Inc.",
  PCAR: "PACCAR Inc.",
  ODFL: "Old Dominion Freight",
  FAST: "Fastenal Co.",
  CTAS: "Cintas Corp.",
  AEP: "American Electric Power",
  EXC: "Exelon Corp.",
  XEL: "Xcel Energy",

  // ── FTSE 100 (UK) ────────────────────────────────────────────────────────
  SHEL: "Shell plc",
  AZN: "AstraZeneca plc",
  HSBA: "HSBC Holdings",
  ULVR: "Unilever plc",
  BP: "BP plc",
  GSK: "GSK plc",
  RIO: "Rio Tinto",
  BHP: "BHP Group",
  BATS: "British American Tobacco",
  DGE: "Diageo plc",
  LLOY: "Lloyds Banking Group",
  BARC: "Barclays plc",
  NWG: "NatWest Group",
  STAN: "Standard Chartered",
  PRU: "Prudential plc",
  LSE: "London Stock Exchange Group",
  "RR.": "Rolls-Royce Holdings",
  VOD: "Vodafone Group",
  "BA.": "BAE Systems",
  TSCO: "Tesco plc",
  "NG.": "National Grid",
  AAL: "Anglo American",
  GLEN: "Glencore plc",
  ANTO: "Antofagasta plc",
  IHG: "InterContinental Hotels",
  CRH: "CRH plc",
  REL: "RELX plc",
  III: "3i Group",
  CCH: "Coca-Cola HBC",
  CPG: "Compass Group",
  SGE: "Sage Group",
  LGEN: "Legal & General",
  "AV.": "Aviva plc",
  ABF: "Associated British Foods",
  "BT.A": "BT Group",
  IMB: "Imperial Brands",
  SVT: "Severn Trent",
  "UU.": "United Utilities",
  RKT: "Reckitt Benckiser",
  EXPN: "Experian plc",
  FERG: "Ferguson plc",
  MNG: "M&G plc",
  NXT: "Next plc",
  "JD.": "JD Sports Fashion",
  LAND: "Land Securities",
  BLND: "British Land",
  SGRO: "Segro plc",
  "SN.": "Smith & Nephew",
  HIK: "Hikma Pharmaceuticals",

  // ── DAX 40 (Germany) ─────────────────────────────────────────────────────
  SAP: "SAP SE",
  SIE: "Siemens AG",
  ALV: "Allianz SE",
  DTE: "Deutsche Telekom",
  MBG: "Mercedes-Benz Group",
  BMW: "BMW AG",
  BAS: "BASF SE",
  BAYN: "Bayer AG",
  DBK: "Deutsche Bank",
  DPW: "Deutsche Post DHL",
  DHL: "DHL Group",
  MUV2: "Munich Re",
  VOW3: "Volkswagen AG",
  ADS: "Adidas AG",
  AIR: "Airbus SE",
  CON: "Continental AG",
  HEN3: "Henkel AG",
  IFX: "Infineon Technologies",
  RWE: "RWE AG",
  EOAN: "E.ON SE",
  HEI: "HeidelbergCement",
  BNR: "Brenntag SE",
  BEI: "Beiersdorf AG",
  SY1: "Symrise AG",
  VNA: "Vonovia SE",
  FRE: "Fresenius SE",
  "1COV": "Covestro AG",
  SHL: "Siemens Healthineers",
  QGEN: "Qiagen NV",
  ZAL: "Zalando SE",
  P911: "Porsche AG",
  MTX: "MTU Aero Engines",
  ENR: "Siemens Energy",
  RHM: "Rheinmetall AG",
  EVK: "Evonik Industries",
  FME: "Fresenius Medical Care",
  HNR1: "Hannover Rück",
  SDF: "K+S AG",
  SRT3: "Sartorius AG",

  // ── CAC 40 (France) ──────────────────────────────────────────────────────
  MC: "LVMH Moët Hennessy",
  TTE: "TotalEnergies SE",
  OR: "L'Oréal SA",
  SAN: "Sanofi SA",
  BNP: "BNP Paribas",
  CS: "AXA SA",
  AI: "Air Liquide",
  DG: "Vinci SA",
  // SU collides with Suncor (TSX) — Schneider Electric covered via SU.PA in heatmap
  KER: "Kering SA",
  RMS: "Hermès International",
  SAF: "Safran SA",
  VIE: "Veolia Environnement",
  GLE: "Société Générale",
  VIV: "Vivendi SE",
  CAP: "Capgemini SE",
  ML: "Michelin",
  ENGI: "Engie SA",
  DSY: "Dassault Systèmes",
  ACA: "Crédit Agricole",
  CA: "Carrefour SA",
  ATO: "Atos SE",
  STMPA: "STMicroelectronics",
  URW: "Unibail-Rodamco-Westfield",
  // BN collides with Brookfield Corp (TSX) — Danone is covered via BN.PA in heatmap
  PUB: "Publicis Groupe",
  HO: "Thales SA",
  LR: "Legrand SA",
  STLAP: "Stellantis NV",
  EL: "EssilorLuxottica",
  RNO: "Renault SA",
  RI: "Pernod Ricard",
  WLN: "Worldline SA",
  SGO: "Saint-Gobain",
  ORA: "Orange SA",
  AMUN: "Amundi SA",
  // BN collides with Brookfield Corp (TSX) — Danone covered via BN.PA in heatmap

  // ── Nikkei 225 (Japan, numeric tickers) ──────────────────────────────────
  "9983": "Fast Retailing (Uniqlo)",
  "8035": "Tokyo Electron",
  "6857": "Advantest Corp.",
  "9984": "SoftBank Group",
  "6098": "Recruit Holdings",
  "8001": "Itochu Corp.",
  "6758": "Sony Group",
  "7203": "Toyota Motor",
  "6861": "Keyence Corp.",
  "4063": "Shin-Etsu Chemical",
  "9433": "KDDI Corp.",
  "4502": "Takeda Pharmaceutical",
  "8316": "Sumitomo Mitsui Financial",
  "8306": "Mitsubishi UFJ Financial",
  "7974": "Nintendo Co.",
  "4543": "Terumo Corp.",
  "6594": "Nidec Corp.",
  "7267": "Honda Motor",
  "9432": "Nippon Telegraph & Telephone",
  "7011": "Mitsubishi Heavy Industries",
  "4519": "Chugai Pharmaceutical",
  "6273": "SMC Corp.",
  "6981": "Murata Manufacturing",
  "6701": "NEC Corp.",
  "8002": "Marubeni Corp.",
  "8058": "Mitsubishi Corp.",
  "8031": "Mitsui & Co.",
  "6367": "Daikin Industries",
  "6326": "Kubota Corp.",
  "7741": "Hoya Corp.",
  "5108": "Bridgestone Corp.",
  "7270": "Subaru Corp.",
  "6503": "Mitsubishi Electric",
  "7751": "Canon Inc.",
  "6645": "Omron Corp.",
  "9020": "East Japan Railway",
  "9501": "Tokyo Electric Power",
  "9024": "Seven & i Holdings",
  "5020": "ENEOS Holdings",
  "8053": "Sumitomo Corp.",
  "8411": "Mizuho Financial Group",
  "8766": "Tokio Marine Holdings",
  "8591": "ORIX Corp.",
  "3382": "Seven & i Holdings (legacy)",

  // ── Shanghai Composite (China, 6-digit tickers) ──────────────────────────
  "601398": "ICBC (Industrial & Commercial Bank of China)",
  "601288": "Agricultural Bank of China",
  "600519": "Kweichow Moutai",
  "601318": "Ping An Insurance",
  "600036": "China Merchants Bank",
  "601988": "Bank of China",
  "601628": "China Life Insurance",
  "601166": "Industrial Bank",
  "601138": "Foxconn Industrial Internet",
  "600028": "Sinopec",
  "601857": "PetroChina",
  "600000": "Shanghai Pudong Development Bank",
  "601658": "Postal Savings Bank of China",
  "600276": "Jiangsu Hengrui Medicine",
  "600585": "Anhui Conch Cement",
  "600438": "Tongwei Co.",
  "600009": "Shanghai International Airport",
  "601668": "China State Construction (CSCEC)",
  "601336": "New China Life Insurance",
  "600196": "Shanghai Fosun Pharmaceutical",
  "601169": "Bank of Beijing",
  "601319": "PICC (People's Insurance Co.)",
  "600547": "Shandong Gold Mining",
  "601800": "China Communications Construction",
  "601088": "China Shenhua Energy",
  "603288": "Foshan Haitian Flavouring",
  "600887": "Inner Mongolia Yili",
  "600600": "Tsingtao Brewery",
  "603799": "Zhejiang Huayou Cobalt",
  "600188": "Yankuang Energy",
  "600703": "Sanan Optoelectronics",
  "603501": "Will Semiconductor",
  "600048": "Poly Developments & Holdings",
  "601155": "Seazen Holdings",
  "603259": "WuXi AppTec",
  "601766": "CRRC Corp.",
  "601229": "Bank of Shanghai",

  // ── KOSPI (Korea, 6-digit with leading zeros) ────────────────────────────
  "005930": "Samsung Electronics",
  "000660": "SK Hynix",
  "005935": "Samsung Electronics (Pfd)",
  "207940": "Samsung Biologics",
  "005380": "Hyundai Motor",
  "035720": "Kakao Corp.",
  "035420": "NAVER Corp.",
  "051910": "LG Chem",
  "006400": "Samsung SDI",
  "005490": "POSCO Holdings",
  "068270": "Celltrion Inc.",
  "105560": "KB Financial Group",
  "055550": "Shinhan Financial Group",
  "086790": "Hana Financial Group",
  "028260": "Samsung C&T",
  "003670": "POSCO Future M",
  "042660": "Hanwha Ocean",
  "015760": "Korea Electric Power",
  "017670": "SK Telecom",
  "030200": "KT Corp.",
  "000270": "Kia Corp.",
  "012330": "Hyundai Mobis",
  "066570": "LG Electronics",
  "003550": "LG Corp.",
  "034730": "SK Holdings",
  "096770": "SK Innovation",
  "028050": "Samsung Engineering",
  "010130": "Korea Zinc",
  "000810": "Samsung Fire & Marine",
  "316140": "Woori Financial Group",
  "138930": "BNK Financial Group",
  "011200": "HMM Co.",
  "034220": "LG Display",
  "011070": "LG Innotek",
  "068760": "Celltrion Pharm",
  "097950": "CJ CheilJedang",

  // ── TAIEX (Taiwan, 4-digit tickers) ──────────────────────────────────────
  // Semiconductors
  "2330": "Taiwan Semiconductor (TSMC)",
  "2454": "MediaTek Inc.",
  "2303": "United Microelectronics (UMC)",
  "3034": "Novatek Microelectronics",
  "3711": "ASE Technology Holding",
  "2474": "Catcher Technology",
  "6488": "Phison Electronics",
  "3661": "Wiwynn Corp.",
  // Tech Hardware / Comms
  "2317": "Hon Hai Precision (Foxconn)",
  "2308": "Delta Electronics",
  "2382": "Quanta Computer",
  "2357": "ASUSTeK Computer",
  "3008": "Largan Precision",
  "2354": "Foxconn Technology",
  "2412": "Chunghwa Telecom",
  // Financial Holdings
  "2881": "Fubon Financial Holding",
  "2882": "Cathay Financial Holding",
  "2891": "CTBC Financial Holding",
  "2885": "Yuanta Financial Holdings",
  "2884": "E.Sun Financial Holding",
  "2886": "Mega Financial Holding",
  "2880": "Hua Nan Financial Holdings",
  "2883": "China Development Financial",
  "2887": "Taishin Financial Holding",
  "5880": "Taiwan Cooperative Financial",
  // Telecom
  "3045": "Taiwan Mobile",
  "4904": "Far EasTone Telecom",
  // Materials & Energy
  "1301": "Formosa Plastics",
  "1303": "Nan Ya Plastics",
  "2002": "China Steel",
  "6505": "Formosa Petrochemical",
  // Consumer
  "1216": "Uni-President Enterprises",
  "2912": "President Chain Store",
  "2207": "Hotai Motor",
  "2105": "Cheng Shin Rubber",
  // Shipping
  "2603": "Evergreen Marine",
  "2615": "Wan Hai Lines",
  "2609": "Yang Ming Marine Transport",
};

export function getCompanyName(ticker: string): string | null {
  return TICKER_NAMES[ticker] ?? null;
}
