// Symbol → full company name lookup for heatmap tooltips.
//
// GENERATED — do not edit by hand. Regenerate with: npm run gen:ticker-names
//
// Keyed by the exchange-qualified Yahoo symbol (0700.HK, BA.L, BRK-B) rather
// than the bare ticker, because bare tickers collide across the 11 indices:
// `T` is AT&T in the S&P 500 but Telus on the TSX, `AIR` is Airbus on both the
// DAX and the CAC, `MRK` is Merck & Co. in the US and Merck KGaA in Germany.
export const TICKER_NAMES: Record<string, string> = {
  // ── S&P 500 ─────────────────────────────────────────────────────
  "NVDA": "NVIDIA Corporation",
  "AAPL": "Apple Inc.",
  "MSFT": "Microsoft Corporation",
  "AMZN": "Amazon.com, Inc.",
  "GOOGL": "Alphabet Inc.",
  "AVGO": "Broadcom Inc.",
  "GOOG": "Alphabet Inc.",
  "META": "Meta Platforms, Inc.",
  "MU": "Micron Technology, Inc.",
  "JPM": "JPMorgan Chase & Co.",
  "LLY": "Eli Lilly and Company",
  "BRK-B": "Berkshire Hathaway Inc.",
  "TSLA": "Tesla, Inc.",
  "AMD": "Advanced Micro Devices, Inc.",
  "XOM": "ExxonMobil Holdings Corporation",
  "JNJ": "Johnson & Johnson",
  "V": "Visa Inc.",
  "WMT": "Walmart Inc.",
  "INTC": "Intel Corporation",
  "CSCO": "Cisco Systems, Inc.",
  "MA": "Mastercard Incorporated",
  "ABBV": "AbbVie Inc.",
  "AMAT": "Applied Materials, Inc.",
  "BAC": "Bank of America Corporation",
  "COST": "Costco Wholesale Corporation",
  "LRCX": "Lam Research Corporation",
  "CAT": "Caterpillar Inc.",
  "PLTR": "Palantir Technologies Inc.",
  "GE": "GE Aerospace",
  "UNH": "UnitedHealth Group Incorporated",
  "CVX": "Chevron Corporation",
  "HD": "The Home Depot, Inc.",
  "KO": "The Coca-Cola Company",
  "PG": "The Procter & Gamble Company",
  "MRK": "Merck & Co., Inc.",
  "PANW": "Palo Alto Networks, Inc.",
  "NFLX": "Netflix, Inc.",
  "GS": "The Goldman Sachs Group, Inc.",
  "RTX": "RTX Corporation",
  "PM": "Philip Morris International Inc.",
  "GEV": "GE Vernova Inc.",
  "WFC": "Wells Fargo & Company",
  "KLAC": "KLA Corporation",
  "MS": "Morgan Stanley",
  "ORCL": "Oracle Corporation",
  "TXN": "Texas Instruments Incorporated",
  "C": "Citigroup Inc.",
  "CRWD": "CrowdStrike Holdings, Inc.",
  "AMGN": "Amgen Inc.",
  "TMO": "Thermo Fisher Scientific Inc.",
  "IBM": "International Business Machines Corporation",
  "LIN": "Linde plc",
  "ANET": "Arista Networks, Inc.",
  "APH": "Amphenol Corporation",
  "SNDK": "Sandisk Corporation",
  "STX": "Seagate Technology Holdings plc",
  "VZ": "Verizon Communications Inc.",
  "MCD": "McDonald's Corporation",
  "ABT": "Abbott Laboratories",
  "MRVL": "Marvell Technology, Inc.",
  "PEP": "PepsiCo, Inc.",
  "ADI": "Analog Devices, Inc.",
  "AXP": "American Express Company",
  "BA": "The Boeing Company",
  "DIS": "The Walt Disney Company",
  "NEE": "NextEra Energy, Inc.",
  "SCHW": "The Charles Schwab Corporation",
  "ETN": "Eaton Corporation plc",
  "UNP": "Union Pacific Corporation",
  "QCOM": "QUALCOMM Incorporated",
  "TJX": "The TJX Companies, Inc.",
  "GILD": "Gilead Sciences, Inc.",
  "T": "AT&T Inc.",
  "BLK": "BlackRock, Inc.",
  "BKNG": "Booking Holdings Inc.",
  "WELL": "Welltower Inc.",
  "CRM": "Salesforce, Inc.",
  "WDC": "Western Digital Corporation",
  "DE": "Deere & Company",
  "COP": "ConocoPhillips",
  "UBER": "Uber Technologies, Inc.",
  "PFE": "Pfizer Inc.",
  "ISRG": "Intuitive Surgical, Inc.",
  "DELL": "Dell Technologies Inc.",
  "COF": "Capital One Financial Corporation",
  "PH": "Parker-Hannifin Corporation",
  "VRTX": "Vertex Pharmaceuticals Incorporated",
  "PLD": "Prologis, Inc.",
  "GLW": "Corning Incorporated",
  "BMY": "Bristol-Myers Squibb Company",
  "DHR": "Danaher Corporation",
  "NOW": "ServiceNow, Inc.",
  "NEM": "Newmont Corporation",
  "SPGI": "S&P Global Inc.",
  "CB": "Chubb Limited",
  "SBUX": "Starbucks Corporation",
  "LMT": "Lockheed Martin Corporation",
  "PGR": "The Progressive Corporation",
  "LOW": "Lowe's Companies, Inc.",
  "CVS": "CVS Health Corporation",
  "SYK": "Stryker Corporation",
  "MDT": "Medtronic plc",
  "HWM": "Howmet Aerospace Inc.",
  "BNY": "The Bank of New York Mellon Cor",
  "VRT": "Vertiv Holdings Co",
  "ACN": "Accenture plc",
  "BX": "Blackstone Inc.",
  "ADP": "Automatic Data Processing, Inc.",
  "MO": "Altria Group, Inc.",
  "TT": "Trane Technologies plc",
  "MCK": "McKesson Corporation",
  "EQIX": "Equinix, Inc.",
  "ADBE": "Adobe Inc.",
  "SO": "The Southern Company",
  "PNC": "The PNC Financial Services Group, Inc.",
  "PWR": "Quanta Services, Inc.",
  "MPC": "Marathon Petroleum Corporation",
  "USB": "U.S. Bancorp",
  "FTNT": "Fortinet, Inc.",
  "GD": "General Dynamics Corporation",
  "FCX": "Freeport-McMoRan Inc.",
  "VLO": "Valero Energy Corporation",
  "DUK": "Duke Energy Corporation",
  "MMM": "3M Company",
  "CME": "CME Group Inc.",
  "JCI": "Johnson Controls International plc",
  "CSX": "CSX Corporation",
  "INTU": "Intuit Inc.",
  "EMR": "Emerson Electric Co.",
  "MRSH": "Marsh & McLennan Companies, Inc.",
  "CMCSA": "Comcast Corporation",
  "PSX": "Phillips 66",
  "WMB": "The Williams Companies, Inc.",
  "CDNS": "Cadence Design Systems, Inc.",
  "CEG": "Constellation Energy Corporation",
  "CMI": "Cummins Inc.",
  "ELV": "Elevance Health, Inc.",
  "ICE": "Intercontinental Exchange, Inc.",
  "WM": "Waste Management, Inc.",
  "SHW": "The Sherwin-Williams Company",
  "TMUS": "T-Mobile US, Inc.",
  "APP": "AppLovin Corporation",
  "DASH": "DoorDash, Inc.",
  "ROST": "Ross Stores, Inc.",
  "MDLZ": "Mondelez International, Inc.",
  "REGN": "Regeneron Pharmaceuticals, Inc.",
  "DDOG": "Datadog, Inc.",
  "AMT": "American Tower Corporation",
  "SNPS": "Synopsys, Inc.",
  "TRV": "The Travelers Companies, Inc.",
  "SLB": "SLB N.V.",
  "GM": "General Motors Company",
  "HPE": "Hewlett Packard Enterprise Company",
  "MSI": "Motorola Solutions, Inc.",
  "MAR": "Marriott International, Inc.",
  "UPS": "United Parcel Service, Inc.",
  "NOC": "Northrop Grumman Corporation",
  "RCL": "Royal Caribbean Cruises Ltd.",
  "KKR": "KKR & Co. Inc.",
  "ITW": "Illinois Tool Works Inc.",
  "BSX": "Boston Scientific Corporation",
  "ORLY": "O'Reilly Automotive, Inc.",
  "EOG": "EOG Resources, Inc.",
  "NSC": "Norfolk Southern Corporation",
  "ABNB": "Airbnb, Inc.",
  "AON": "Aon plc",
  "HOOD": "Robinhood Markets, Inc.",
  "HON": "Honeywell International Inc.",
  "CL": "Colgate-Palmolive Company",
  "HLT": "Hilton Worldwide Holdings Inc.",
  "CI": "The Cigna Group",
  "LITE": "Lumentum Holdings Inc.",
  "MCO": "Moody's Corporation",
  "FDX": "FedEx Corporation",
  "SPG": "Simon Property Group, Inc.",
  "URI": "United Rentals, Inc.",
  "ECL": "Ecolab Inc.",
  "MPWR": "Monolithic Power Systems, Inc.",
  "TGT": "Target Corporation",
  "COHR": "Coherent Corp.",
  "CTAS": "Cintas Corporation",
  "TDG": "TransDigm Group Incorporated",
  "PCAR": "PACCAR Inc",
  "DLR": "Digital Realty Trust, Inc.",
  "WBD": "Warner Bros. Discovery, Inc.",
  "AEP": "American Electric Power Company, Inc.",
  "APD": "Air Products and Chemicals, Inc.",
  "ALL": "The Allstate Corporation",
  "MNST": "Monster Beverage Corporation",
  "TFC": "Truist Financial Corporation",
  "AJG": "Arthur J. Gallagher & Co.",
  "CRH": "CRH plc",
  "HCA": "HCA Healthcare, Inc.",
  "APO": "Apollo Global Management, Inc.",
  "BKR": "Baker Hughes Company",
  "TER": "Teradyne, Inc.",
  "TEL": "TE Connectivity plc",
  "KMI": "Kinder Morgan, Inc.",
  "NUE": "Nucor Corporation",
  "COR": "Cencora, Inc.",
  "CIEN": "Ciena Corporation",
  "FIX": "Comfort Systems USA, Inc.",
  "KEYS": "Keysight Technologies, Inc.",
  "FAST": "Fastenal Company",
  "D": "Dominion Energy, Inc.",
  "AME": "AMETEK, Inc.",
  "NXPI": "NXP Semiconductors N.V.",
  "DAL": "Delta Air Lines, Inc.",
  "O": "Realty Income Corporation",
  "OKE": "ONEOK, Inc.",
  "TRGP": "Targa Resources Corp.",
  "GWW": "W.W. Grainger, Inc.",
  "SRE": "Sempra",
  "AFL": "Aflac Incorporated",
  "CAH": "Cardinal Health, Inc.",
  "PSA": "Public Storage",
  "LHX": "L3Harris Technologies, Inc.",
  "F": "Ford Motor Company",
  "EW": "Edwards Lifesciences Corporation",
  "HONA": "Honeywell Aerospace Inc.",
  "ADSK": "Autodesk, Inc.",
  "STT": "State Street Corporation",
  "FITB": "Fifth Third Bancorp",
  "MET": "MetLife, Inc.",
  "PYPL": "PayPal Holdings, Inc.",
  "CVNA": "Carvana Co.",
  "DVN": "Devon Energy Corporation",
  "AMP": "Ameriprise Financial, Inc.",
  "GRMN": "Garmin Ltd.",
  "BDX": "Becton, Dickinson and Company",
  "CTVA": "Corteva, Inc.",
  "AZO": "AutoZone, Inc.",
  "ROK": "Rockwell Automation, Inc.",
  "WAB": "Westinghouse Air Brake Technologies Corporation",
  "ETR": "Entergy Corporation",
  "CARR": "Carrier Global Corporation",
  "XEL": "Xcel Energy Inc.",
  "NKE": "NIKE, Inc.",
  "AXON": "Axon Enterprise, Inc.",
  "FERG": "Ferguson Enterprises Inc.",
  "HUM": "Humana Inc.",
  "VST": "Vistra Corp.",
  "EXC": "Exelon Corporation",
  "FLEX": "Flex Ltd.",
  "EBAY": "eBay Inc.",
  "IDXX": "IDEXX Laboratories, Inc.",
  "VTR": "Ventas, Inc.",
  "CBRE": "CBRE Group, Inc.",
  "MCHP": "Microchip Technology Incorporated",
  "RSG": "Republic Services, Inc.",

  // ── NASDAQ 100 ──────────────────────────────────────────────────
  "SPCX": "Space Exploration Technologies Corp.",
  "SHOP": "Shopify Inc.",
  "ASML": "ASML Holding N.V.",
  "ARM": "Arm Holdings plc",
  "MELI": "MercadoLibre, Inc.",
  "PDD": "PDD Holdings Inc.",
  "EA": "Electronic Arts Inc.",
  "CCEP": "Coca-Cola Europacific Partners PLC",
  "ODFL": "Old Dominion Freight Line, Inc.",
  "TTWO": "Take-Two Interactive Software, Inc.",
  "ALAB": "Astera Labs, Inc.",
  "FER": "Ferrovial N.V.",
  "PAYX": "Paychex, Inc.",
  "KDP": "Keurig Dr Pepper Inc.",
  "TRI": "Thomson Reuters Corporation",
  "ROP": "Roper Technologies, Inc.",
  "ALNY": "Alnylam Pharmaceuticals, Inc.",
  "NBIS": "Nebius Group N.V.",
  "RKLB": "Rocket Lab Corporation",
  "WDAY": "Workday, Inc.",
  "MSTR": "Strategy Inc",
  "KHC": "The Kraft Heinz Company",
  "CRWV": "CoreWeave, Inc.",
  "DXCM": "DexCom, Inc.",
  "CPRT": "Copart, Inc.",
  "GEHC": "GE HealthCare Technologies Inc.",

  // ── S&P/TSX ─────────────────────────────────────────────────────
  "RY.TO": "Royal Bank of Canada",
  "TD.TO": "The Toronto-Dominion Bank",
  "SHOP.TO": "Shopify Inc.",
  "BMO.TO": "Bank of Montreal",
  "ENB.TO": "Enbridge Inc.",
  "CM.TO": "Canadian Imperial Bank of Commerce",
  "BNS.TO": "The Bank of Nova Scotia",
  "CNQ.TO": "Canadian Natural Resources Limited",
  "BN.TO": "Brookfield Corporation",
  "AEM.TO": "Agnico Eagle Mines Limited",
  "CP.TO": "Canadian Pacific Kansas City Limited",
  "SU.TO": "Suncor Energy Inc.",
  "MFC.TO": "Manulife Financial Corporation",
  "ABX.TO": "Barrick Mining Corporation",
  "CNR.TO": "Canadian National Railway Company",
  "TRP.TO": "TC Energy Corporation",
  "NA.TO": "National Bank of Canada",
  "WPM.TO": "Wheaton Precious Metals Corp.",
  "ATD.TO": "Alimentation Couche-Tard Inc.",
  "FNV.TO": "Franco-Nevada Corporation",
  "SLF.TO": "Sun Life Financial Inc.",
  "CSU.TO": "Constellation Software Inc.",
  "CCO.TO": "Cameco Corporation",
  "CLS.TO": "Celestica Inc.",
  "WCN.TO": "Waste Connections, Inc.",
  "CVE.TO": "Cenovus Energy Inc.",
  "DOL.TO": "Dollarama Inc.",
  "POW.TO": "Power Corporation of Canada",
  "IFC.TO": "Intact Financial Corporation",
  "FFH.TO": "Fairfax Financial Holdings Limited",
  "K.TO": "Kinross Gold Corporation",
  "NTR.TO": "Nutrien Ltd.",
  "TECK-B.TO": "Teck Resources Limited",
  "FTS.TO": "Fortis Inc.",
  "PPL.TO": "Pembina Pipeline Corporation",
  "QSR.TO": "Restaurant Brands International Inc.",
  "L.TO": "Loblaw Companies Limited",
  "PAAS.TO": "Pan American Silver Corp.",
  "BBD-B.TO": "Bombardier Inc.",
  "BCE.TO": "BCE Inc.",
  "FM.TO": "First Quantum Minerals Ltd.",
  "BAM.TO": "Brookfield Asset Management Ltd.",
  "IMO.TO": "Imperial Oil Limited",
  "WSP.TO": "WSP Global Inc.",
  "BIP-UN.TO": "Brookfield Infrastructure Partners L.P.",
  "MG.TO": "Magna International Inc.",
  "LUN.TO": "Lundin Mining Corporation",
  "GWO.TO": "Great-West Lifeco Inc.",
  "RBA.TO": "RB Global, Inc.",
  "TOU.TO": "Tourmaline Oil Corp.",
  "EMA.TO": "Emera Incorporated",
  "T.TO": "TELUS Corporation",
  "WCP.TO": "Whitecap Resources Inc.",
  "AGI.TO": "Alamos Gold Inc.",
  "GIB-A.TO": "CGI Inc.",
  "RCI-B.TO": "Rogers Communications Inc.",
  "TRI.TO": "Thomson Reuters Corporation",
  "ARX.TO": "ARC Resources Ltd.",
  "IAG.TO": "iA Financial Corporation Inc.",
  "H.TO": "Hydro One Limited",
  "TIH.TO": "Toromont Industries Ltd.",
  "HBM.TO": "Hudbay Minerals Inc.",
  "MRU.TO": "Metro Inc.",
  "EQX.TO": "Equinox Gold Corp.",
  "ALA.TO": "AltaGas Ltd.",
  "KEY.TO": "Keyera Corp.",
  "TFII.TO": "TFI International Inc.",
  "WN.TO": "George Weston Limited",
  "GFL.TO": "GFL Environmental Inc.",
  "X.TO": "TMX Group Limited",
  "GIL.TO": "Gildan Activewear Inc.",
  "IMG.TO": "IAMGOLD Corporation",
  "ATRL.TO": "AtkinsRéalis Group Inc.",
  "DPM.TO": "DPM Metals Inc.",
  "ATZ.TO": "Aritzia Inc.",
  "ELD.TO": "Eldorado Gold Corporation",
  "CCL-B.TO": "CCL Industries Inc.",
  "AG.TO": "First Majestic Silver Corp.",
  "CAE.TO": "CAE Inc.",
  "FTT.TO": "Finning International Inc.",
  "STN.TO": "Stantec Inc.",
  "EFN.TO": "Element Fleet Management Corp.",
  "BEP-UN.TO": "Brookfield Renewable Partners L.P.",
  "SOBO.TO": "South Bow Corporation",
  "GMIN.TO": "G Mining Ventures Corp.",
  "SAP.TO": "Saputo Inc.",
  "CPX.TO": "Capital Power Corporation",
  "CTC-A.TO": "Canadian Tire Corporation, Limited",
  "CS.TO": "Capstone Copper Corp.",
  "QBR-B.TO": "Quebecor Inc.",
  "SSRM.TO": "SSR Mining Inc.",
  "NXE.TO": "NexGen Energy Ltd.",
  "BTO.TO": "B2Gold Corp.",
  "DSG.TO": "The Descartes Systems Group Inc.",
  "LUG.TO": "Lundin Gold Inc.",
  "OGC.TO": "OceanaGold Corporation",
  "IVN.TO": "Ivanhoe Mines Ltd.",
  "OR.TO": "OR Royalties Inc.",
  "AC.TO": "Air Canada",
  "FSV.TO": "FirstService Corporation",
  "OTEX.TO": "Open Text Corporation",
  "PSK.TO": "PrairieSky Royalty Ltd.",
  "MDA.TO": "MDA Space Ltd.",
  "DFY.TO": "Definity Financial Corporation",
  "KNT.TO": "K92 Mining Inc.",
  "EIF.TO": "Exchange Income Corporation",
  "IGM.TO": "IGM Financial Inc.",
  "CSH-UN.TO": "Chartwell Retirement Residences",
  "DSV.TO": "Discovery Mining Ltd.",
  "CU.TO": "Canadian Utilities Limited",
  "ONEX.TO": "Onex Corporation",
  "BB.TO": "BlackBerry Limited",
  "TVE.TO": "Tamarack Valley Energy Ltd.",
  "EMP-A.TO": "Empire Company Limited",
  "REI-UN.TO": "RioCan Real Estate Investment Trust",
  "CIGI.TO": "Colliers International Group Inc.",
  "CG.TO": "Centerra Gold Inc.",
  "MAU.TO": "Montage Gold Corp.",
  "TXG.TO": "Torex Gold Resources Inc.",
  "SKE.TO": "Skeena Resources Limited",
  "NPI.TO": "Northland Power Inc.",
  "AQN.TO": "Algonquin Power & Utilities Corp.",
  "GRT-UN.TO": "Granite Real Estate Investment Trust",
  "GEI.TO": "Gibson Energy Inc.",
  "ACO-X.TO": "ATCO Ltd.",
  "WFG.TO": "West Fraser Timber Co. Ltd.",
  "ERO.TO": "Ero Copper Corp.",
  "AYA.TO": "Aya Gold & Silver Inc.",
  "CAR-UN.TO": "Canadian Apartment Properties Real Estate Investment Trust",
  "ATH.TO": "Athabasca Oil Corporation",
  "ARIS.TO": "Aris Mining Corporation",
  "EFR.TO": "Energy Fuels Inc.",
  "PEY.TO": "Peyto Exploration & Development Corp.",
  "WDO.TO": "Wesdome Gold Mines Ltd.",
  "MX.TO": "Methanex Corporation",
  "TA.TO": "TransAlta Corporation",
  "FCR-UN.TO": "First Capital Real Estate Investment Trust",
  "KXS.TO": "Kinaxis Inc.",
  "FVI.TO": "Fortuna Mining Corp.",
  "TKO.TO": "Trekor Metals Limited",
  "EDR.TO": "Endeavour Silver Corp.",
  "RUS.TO": "Russel Metals Inc.",
  "SES.TO": "SECURE Waste Infrastructure Corp.",
  "CHP-UN.TO": "Choice Properties Real Estate Investment Trust",
  "LNR.TO": "Linamar Corporation",
  "SJ.TO": "Stella-Jones Inc.",
  "BYD.TO": "Boyd Group Services Inc.",
  "CEU.TO": "CES Energy Solutions Corp.",
  "SEA.TO": "Seabridge Gold Inc.",
  "DIR-UN.TO": "Dream Industrial Real Estate Investment Trust",
  "DML.TO": "Denison Mines Corp.",
  "BTE.TO": "Baytex Energy Corp.",
  "NGEX.TO": "NGEx Minerals Ltd.",
  "SVM.TO": "Silvercorp Metals Inc.",
  "SRU-UN.TO": "SmartCentres Real Estate Investment Trust",
  "EQB.TO": "EQB Inc.",
  "EFX.TO": "Enerflex Ltd.",
  "PBH.TO": "Premium Brands Holdings Corporation",
  "BDT.TO": "Bird Construction Inc.",
  "SII.TO": "Sprott Inc.",
  "TPZ.TO": "Topaz Energy Corp.",
  "DOO.TO": "BRP Inc.",
  "BLX.TO": "Boralex Inc.",
  "NG.TO": "NovaGold Resources Inc.",
  "TFPM.TO": "Triple Flag Precious Metals Corp.",
  "SXGC.TO": "Southern Cross Gold Consolidated Ltd.",
  "ARE.TO": "Aecon Group Inc.",
  "AAUC.TO": "Allied Gold Corporation",
  "HWX.TO": "Headwater Exploration Inc.",
  "BDGI.TO": "Badger Infrastructure Solutions Ltd.",
  "ALS.TO": "Altius Minerals Corporation",
  "PPTA.TO": "Perpetua Resources Corp.",
  "HR-UN.TO": "H&R Real Estate Investment Trust",
  "VNP.TO": "5N Plus Inc.",
  "BBUC.TO": "Brookfield Business Corporation",
  "ABRA.TO": "AbraSilver Resource Corp.",
  "PMZ-UN.TO": "Primaris Real Estate Investment Trust",
  "PXT.TO": "Parex Resources Inc.",
  "BEI-UN.TO": "Boardwalk Real Estate Investment Trust",
  "POU.TO": "Paramount Resources Ltd.",
  "EXE.TO": "Extendicare Inc.",
  "VET.TO": "Vermilion Energy Inc.",
  "MTL.TO": "Mullen Group Ltd.",
  "NFI.TO": "NFI Group Inc.",
  "ATS.TO": "ATS Corporation",
  "SIA.TO": "Sienna Senior Living Inc.",
  "FRU.TO": "Freehold Royalties Ltd.",
  "CURA.TO": "Curaleaf Holdings, Inc.",
  "NWC.TO": "The North West Company Inc.",
  "BHC.TO": "Bausch Health Companies Inc.",
  "HPS-A.TO": "Hammond Power Solutions Inc.",
  "KMP-UN.TO": "Killam Apartment REIT",
  "SDE.TO": "Spartan Delta Corp.",
  "IPCO.TO": "International Petroleum Corporation",
  "IAU.TO": "i-80 Gold Corp.",
  "MFI.TO": "Maple Leaf Foods Inc.",
  "TSU.TO": "Trisura Group Ltd.",
  "JWEL.TO": "Jamieson Wellness Inc.",
  "RCH.TO": "Richelieu Hardware Ltd.",
  "LSPD.TO": "Lightspeed Commerce Inc.",
  "AAV.TO": "Advantage Energy Ltd.",
  "TVK.TO": "TerraVest Industries Inc.",
  "CRR-UN.TO": "Crombie Real Estate Investment Trust",
  "VZLA.TO": "Vizsla Silver Corp.",
  "SCR.TO": "Strathcona Resources Ltd.",
  "CCA.TO": "Cogeco Communications Inc.",
  "LB.TO": "Laurentian Bank of Canada",
  "BIR.TO": "Birchcliff Energy Ltd.",
  "AIF.TO": "Altus Group Limited",
  "LIF.TO": "Labrador Iron Ore Royalty Corporation",
  "SPB.TO": "Superior Plus Corp.",
  "ASM.TO": "Avino Silver & Gold Mines Ltd.",
  "KEL.TO": "Kelt Exploration Ltd.",
  "AP-UN.TO": "Allied Properties Real Estate Investment Trust",
  "USA.TO": "Americas Gold and Silver Corporation",
  "CJT.TO": "Cargojet Inc.",
  "LAC.TO": "Lithium Americas Corp.",
  "CRT-UN.TO": "CT Real Estate Investment Trust",

  // ── FTSE 100 ────────────────────────────────────────────────────
  "HSBA.L": "HSBC Holdings plc",
  "AZN.L": "AstraZeneca PLC",
  "SHEL.L": "Shell plc",
  "RR.L": "Rolls-Royce Holdings plc",
  "ULVR.L": "Unilever PLC",
  "BATS.L": "British American Tobacco p.l.c.",
  "BP.L": "BP p.l.c.",
  "GSK.L": "GSK plc",
  "RIO.L": "Rio Tinto Group",
  "BARC.L": "Barclays PLC",
  "LLOY.L": "Lloyds Banking Group plc",
  "NG.L": "National Grid plc",
  "BA.L": "BAE Systems plc",
  "NWG.L": "NatWest Group plc",
  "GLEN.L": "Glencore plc",
  "REL.L": "RELX PLC",
  "LSEG.L": "London Stock Exchange Group plc",
  "CPG.L": "Compass Group PLC",
  "AAL.L": "Anglo American plc",
  "STAN.L": "Standard Chartered PLC",
  "DGE.L": "Diageo plc",
  "HLN.L": "Haleon plc",
  "RKT.L": "Reckitt Benckiser Group plc",
  "TSCO.L": "Tesco PLC",
  "III.L": "3i Group Ord",
  "SSE.L": "SSE plc",
  "PRU.L": "Prudential plc",
  "EXPN.L": "Experian plc",
  "VOD.L": "Vodafone Group Public Limited Company",
  "IMB.L": "Imperial Brands PLC",
  "AV.L": "Aviva plc",
  "NXT.L": "NEXT plc",
  "IHG.L": "InterContinental Hotels Group PLC",
  "CCEP.L": "Coca-Cola Europacific Partners PLC",
  "LGEN.L": "Legal & General Group Plc",
  "IAG.L": "International Consolidated Airlines Group S.A.",
  "SMT.L": "Scottish Mortgage Investment Trust",
  "SGRO.L": "SEGRO Plc",
  "HLMA.L": "Halma plc",
  "ANTO.L": "Antofagasta plc",
  "INF.L": "Informa plc",
  "BT-A.L": "BT Group plc",
  "RTO.L": "Rentokil Initial plc",
  "SN.L": "Smith & Nephew plc",
  "UU.L": "United Utilities Group PLC",
  "CCH.L": "Coca-Cola HBC AG",
  "DPLM.L": "Diploma PLC",
  "ADM.L": "Admiral Group plc",
  "ITRK.L": "Intertek Group plc",
  "BNZL.L": "Bunzl plc",
  "SGE.L": "The Sage Group plc",
  "SVT.L": "Severn Trent PLC",
  "SMIN.L": "Smiths Group plc",
  "PSON.L": "Pearson plc",
  "MKS.L": "Marks and Spencer Group plc",
  "EDV.L": "Endeavour Mining plc",
  "BEZ.L": "Beazley plc",
  "IMI.L": "IMI plc",
  "CNA.L": "Centrica plc",
  "MNG.L": "M&G plc",
  "SDLF.L": "Standard Life plc",
  "SBRY.L": "J Sainsbury plc",
  "PCT.L": "Polar Capital Technology Trust",
  "GAW.L": "Games Workshop Group PLC",
  "WEIR.L": "The Weir Group PLC",
  "FCIT.L": "F&C Investment Trust",
  "HSX.L": "Hiscox Ltd",
  "MRO.L": "Melrose Industries PLC",
  "BAB.L": "Babcock International Group PLC",
  "ABF.L": "Associated British Foods plc",
  "IGG.L": "IG Group Holdings plc",
  "STJ.L": "St. James's Place plc",
  "DCC.L": "DCC Energy plc",
  "ICG.L": "ICG plc",
  "LAND.L": "Land Securities Group Plc",
  "KGF.L": "Kingfisher plc",
  "SPX.L": "Spirax Group plc",
  "ALW.L": "Alliance Witan",
  "FRES.L": "Fresnillo plc",
  "PSH.L": "Pershing Square Holdings, Ltd.",
  "SDR.L": "Schroders plc",
  "BLND.L": "British Land Company PLC",
  "CTEC.L": "Convatec Group PLC",
  "ABDN.L": "Aberdeen Group Plc",
  "AUTO.L": "Autotrader Group plc",
  "LMP.L": "LondonMetric Property Plc",
  "CRDA.L": "Croda International Plc",
  "BBOX.L": "Tritax Big Box REIT",
  "MTLN.L": "Metlen Energy & Metals PLC",
  "WTB.L": "Whitbread plc",
  "HWDN.L": "Howden Joinery Group Plc",
  "BRBY.L": "Burberry Group plc",
  "BGEO.L": "Lion Finance Group PLC",
  "BTRW.L": "Barratt Redrow plc",
  "INVP.L": "Investec Group",
  "PSN.L": "Persimmon Plc",
  "ENT.L": "Entain Plc",
  "CCC.L": "Computacenter plc",
  "AAF.L": "Airtel Africa Plc",
  "JD.L": "JD Sports Fashion Plc",

  // ── DAX ─────────────────────────────────────────────────────────
  "SIE.DE": "Siemens Aktiengesellschaft",
  "SAP.DE": "SAP SE",
  "ALV.DE": "Allianz SE",
  "ENR.DE": "Siemens Energy AG",
  "AIR.DE": "Airbus SE",
  "DTE.DE": "Deutsche Telekom AG",
  "RHM.DE": "Rheinmetall AG",
  "MUV2.DE": "Münchener Rückversicherungs-Gesellschaft Aktiengesellschaft in München",
  "DBK.DE": "Deutsche Bank Aktiengesellschaft",
  "IFX.DE": "Infineon Technologies AG",
  "DHL.DE": "Deutsche Post AG",
  "BAYN.DE": "Bayer Aktiengesellschaft",
  "MBG.DE": "Mercedes-Benz Group AG",
  "BAS.DE": "BASF SE",
  "DB1.DE": "Deutsche Börse AG",
  "EOAN.DE": "E.ON SE",
  "RWE.DE": "RWE Aktiengesellschaft",
  "HEI.DE": "Heidelberg Materials AG",
  "ADS.DE": "adidas AG",
  "BMW.DE": "Bayerische Motoren Werke Aktiengesellschaft",
  "CBK.DE": "Commerzbank AG",
  "DTG.DE": "Daimler Truck Holding AG",
  "VOW3.DE": "Volkswagen AG",
  "MTX.DE": "MTU Aero Engines AG",
  "FRE.DE": "Fresenius SE & Co. KGaA",
  "VNA.DE": "Vonovia SE",
  "MRK.DE": "Merck KGaA",
  "SHL.DE": "Siemens Healthineers AG",
  "HNR1.DE": "Hannover Rück SE",
  "HEN3.DE": "Henkel AG & Co. KGaA",
  "SY1.DE": "Symrise AG",
  "QIA.DE": "Qiagen N.V.",
  "G1A.DE": "GEA Group Aktiengesellschaft",
  "BEI.DE": "Beiersdorf Aktiengesellschaft",
  "FME.DE": "Fresenius Medical Care AG",
  "CON.DE": "Continental Aktiengesellschaft",
  "G24.DE": "Scout24 SE",
  "BNR.DE": "Brenntag SE",
  "ZAL.DE": "Zalando SE",
  "PAH3.DE": "Porsche Automobil Holding SE",

  // ── CAC 40 ──────────────────────────────────────────────────────
  "SU.PA": "Schneider Electric S.E.",
  "MC.PA": "LVMH Moët Hennessy - Louis Vuitton, Société Européenne",
  "AIR.PA": "Airbus SE",
  "SAN.PA": "Sanofi",
  "TTE.PA": "TotalEnergies SE",
  "OR.PA": "L'Oréal S.A.",
  "BNP.PA": "BNP Paribas SA",
  "SAF.PA": "Safran SA",
  "AI.PA": "L'Air Liquide S.A.",
  "EL.PA": "EssilorLuxottica Société anonyme",
  "CS.PA": "AXA SA",
  "RMS.PA": "Hermès International Société en commandite par actions",
  "DG.PA": "Vinci SA",
  "BN.PA": "Danone S.A.",
  "ENGI.PA": "Engie SA",
  "GLE.PA": "Société Générale Société anonyme",
  "SGO.PA": "Compagnie de Saint-Gobain S.A.",
  "LR.PA": "Legrand SA",
  "ORA.PA": "Orange S.A.",
  "CAP.PA": "Capgemini SE",
  "VIE.PA": "Veolia Environnement SA",
  "ML.PA": "Michelin",
  "PUB.PA": "Publicis Groupe S.A.",
  "KER.PA": "Kering SA",
  "DSY.PA": "Dassault Systèmes SE",
  "URW.PA": "Unibail-Rodamco-Westfield SE",
  "STMPA.PA": "STMicroelectronics N.V.",
  "AC.PA": "Accor SA",
  "HO.PA": "Thales S.A.",
  "BVI.PA": "Bureau Veritas SA",
  "ACA.PA": "Crédit Agricole S.A.",
  "STLAP.PA": "Stellantis N.V.",
  "RI.PA": "Pernod Ricard SA",
  "CA.PA": "Carrefour SA",
  "EN.PA": "Bouygues SA",
  "MT.AS": "ArcelorMittal S.A.",
  "RNO.PA": "Renault SA",
  "ENX.PA": "Euronext N.V.",
  "ERF.PA": "Eurofins Scientific SE",
  "FGR.PA": "Eiffage SA",

  // ── NIFTY 50 ────────────────────────────────────────────────────
  "RELIANCE.NS": "Reliance Industries Limited",
  "BHARTIARTL.NS": "Bharti Airtel Limited",
  "HDFCBANK.NS": "HDFC Bank Limited",
  "ICICIBANK.NS": "ICICI Bank Limited",
  "SBIN.NS": "State Bank of India",
  "TCS.NS": "Tata Consultancy Services Limited",
  "BAJFINANCE.NS": "Bajaj Finance Limited",
  "LT.NS": "Larsen & Toubro Limited",
  "HINDUNILVR.NS": "Hindustan Unilever Limited",
  "INFY.NS": "Infosys Limited",
  "SUNPHARMA.NS": "Sun Pharmaceutical Industries Limited",
  "TITAN.NS": "Titan Company Limited",
  "MARUTI.NS": "Maruti Suzuki India Limited",
  "M&M.NS": "Mahindra & Mahindra Limited",
  "ADANIENT.NS": "Adani Enterprises Limited",
  "KOTAKBANK.NS": "Kotak Mahindra Bank Limited",
  "ADANIPORTS.NS": "Adani Ports and Special Economic Zone Limited",
  "AXISBANK.NS": "Axis Bank Limited",
  "HCLTECH.NS": "HCL Technologies Limited",
  "ITC.NS": "ITC Limited",
  "ULTRACEMCO.NS": "UltraTech Cement Limited",
  "NTPC.NS": "NTPC Limited",
  "BAJAJFINSV.NS": "Bajaj Finserv Ltd.",
  "BAJAJ-AUTO.NS": "Bajaj Auto Limited",
  "JSWSTEEL.NS": "JSW Steel Limited",
  "ETERNAL.NS": "Eternal Limited",
  "BEL.NS": "Bharat Electronics Limited",
  "ONGC.NS": "Oil and Natural Gas Corporation Limited",
  "SHRIRAMFIN.NS": "Shriram Finance Limited",
  "ASIANPAINT.NS": "Asian Paints Limited",
  "COALINDIA.NS": "Coal India Limited",
  "POWERGRID.NS": "Power Grid Corporation of India Limited",
  "HINDALCO.NS": "Hindalco Industries Limited",
  "TATASTEEL.NS": "Tata Steel Limited",
  "EICHERMOT.NS": "Eicher Motors Limited",
  "GRASIM.NS": "Grasim Industries Limited",
  "INDIGO.NS": "InterGlobe Aviation Limited",
  "SBILIFE.NS": "SBI Life Insurance Company Limited",
  "WIPRO.NS": "Wipro Limited",
  "JIOFIN.NS": "Jio Financial Services Limited",
  "NESTLEIND.NS": "Nestlé India Limited",
  "TECHM.NS": "Tech Mahindra Limited",
  "TRENT.NS": "Trent Limited",
  "TMPV.NS": "Tata Motors Passenger Vehicles Limited",
  "APOLLOHOSP.NS": "Apollo Hospitals Enterprise Limited",
  "CIPLA.NS": "Cipla Limited",
  "HDFCLIFE.NS": "HDFC Life Insurance Company Limited",
  "TATACONSUM.NS": "Tata Consumer Products Limited",
  "DRREDDY.NS": "Dr. Reddy's Laboratories Limited",
  "MAXHEALTH.NS": "Max Healthcare Institute Limited",

  // ── Nikkei 225 ──────────────────────────────────────────────────
  "6857.T": "Advantest Corporation",
  "9983.T": "Fast Retailing Co., Ltd.",
  "8035.T": "Tokyo Electron Limited",
  "9984.T": "SoftBank Group Corp.",
  "6762.T": "TDK Corporation",
  "6098.T": "Recruit Holdings Co., Ltd.",
  "6954.T": "Fanuc Corporation",
  "9433.T": "KDDI Corporation",
  "4062.T": "Ibiden Co.,Ltd.",
  "285A.T": "KIOXIA HOLDINGS CORPORATION",
  "6971.T": "Kyocera Corporation",
  "4063.T": "Shin-Etsu Chemical Co., Ltd.",
  "5803.T": "Fujikura Ltd.",
  "6367.T": "Daikin Industries,Ltd.",
  "4519.T": "Chugai Pharmaceutical Co., Ltd.",
  "9766.T": "Konami Group Corporation",
  "8015.T": "Toyota Tsusho Corporation",
  "6758.T": "Sony Group Corporation",
  "4543.T": "Terumo Corporation",
  "6981.T": "Murata Manufacturing Co., Ltd.",
  "6988.T": "Nitto Denko Corporation",
  "7203.T": "Toyota Motor Corporation",
  "6920.T": "Lasertec Corporation",
  "8058.T": "Mitsubishi Corporation",
  "7832.T": "BANDAI NAMCO Holdings Inc.",
  "9735.T": "SECOM CO., LTD.",
  "7741.T": "HOYA Corporation",
  "8766.T": "Tokio Marine Holdings, Inc.",
  "6146.T": "Disco Corporation",
  "4901.T": "FUJIFILM Holdings Corporation",
  "4578.T": "Otsuka Holdings Co., Ltd.",
  "4503.T": "Astellas Pharma Inc.",
  "6976.T": "Taiyo Yuden Co., Ltd.",
  "7735.T": "SCREEN Holdings Co., Ltd.",
  "8001.T": "ITOCHU Corporation",
  "2802.T": "Ajinomoto Co., Inc.",
  "8031.T": "Mitsui & Co., Ltd.",
  "7267.T": "Honda Motor Co., Ltd.",
  "5802.T": "Sumitomo Electric Industries, Ltd.",
  "4507.T": "Shionogi & Co., Ltd.",
  "7453.T": "Ryohin Keikaku Co., Ltd.",
  "7269.T": "Suzuki Motor Corporation",
  "2801.T": "Kikkoman Corporation",
  "6861.T": "Keyence Corporation",
  "5108.T": "Bridgestone Corporation",
  "6902.T": "DENSO Corporation",
  "4568.T": "Daiichi Sankyo Company, Limited",
  "7974.T": "Nintendo Co., Ltd.",
  "4021.T": "Nissan Chemical Corporation",
  "7733.T": "Olympus Corporation",
  "8830.T": "Sumitomo Realty & Development Co., Ltd.",
  "6532.T": "Baycurrent, Inc.",
  "2914.T": "Japan Tobacco Inc.",
  "6273.T": "SMC Corporation",
  "6301.T": "Komatsu Ltd.",
  "8053.T": "Sumitomo Corporation",
  "7751.T": "Canon Inc.",
  "4452.T": "Kao Corporation",
  "8591.T": "ORIX Corporation",
  "9843.T": "Nitori Holdings Co., Ltd.",
  "4704.T": "Trend Micro Incorporated",
  "3382.T": "Seven & i Holdings Co., Ltd.",
  "6503.T": "Mitsubishi Electric Corporation",
  "6724.T": "Seiko Epson Corporation",
  "6841.T": "Yokogawa Electric Corporation",
  "5333.T": "NGK Corporation",
  "6361.T": "Ebara Corporation",
  "4502.T": "Takeda Pharmaceutical Company Limited",
  "6645.T": "OMRON Corporation",
  "6305.T": "Hitachi Construction Machinery Co., Ltd.",
  "1721.T": "COMSYS Holdings Corporation",
  "6501.T": "Hitachi, Ltd.",
  "8002.T": "Marubeni Corporation",
  "3659.T": "NEXON Co., Ltd.",
  "2502.T": "Asahi Group Holdings, Ltd.",
  "6506.T": "YASKAWA Electric Corporation",
  "4523.T": "Eisai Co., Ltd.",
  "4307.T": "Nomura Research Institute, Ltd.",
  "8801.T": "Mitsui Fudosan Co., Ltd.",
  "1925.T": "Daiwa House Industry Co., Ltd.",
  "8253.T": "Credit Saison Co., Ltd.",
  "8725.T": "MS&AD Insurance Group Holdings, Inc.",
  "8697.T": "Japan Exchange Group, Inc.",
  "6963.T": "ROHM Co., Ltd.",
  "4385.T": "Mercari, Inc.",
  "6752.T": "Panasonic Holdings Corporation",
  "2413.T": "M3, Inc.",
  "8630.T": "Sompo Holdings, Inc.",
  "5713.T": "Sumitomo Metal Mining Co., Ltd.",
  "8267.T": "Aeon Co., Ltd.",
  "7272.T": "Yamaha Motor Co., Ltd.",
  "8802.T": "Mitsubishi Estate Co., Ltd.",
  "5101.T": "The Yokohama Rubber Company, Limited",
  "7011.T": "Mitsubishi Heavy Industries, Ltd.",
  "7951.T": "Yamaha Corporation",
  "6479.T": "MINEBEA MITSUMI Inc.",
  "6702.T": "Fujitsu Limited",
  "3099.T": "Isetan Mitsukoshi Holdings Ltd.",
  "8306.T": "Mitsubishi UFJ Financial Group, Inc.",
  "4324.T": "Dentsu Group Inc.",
  "5332.T": "TOTO LTD.",
  "1928.T": "Sekisui House, Ltd.",
  "6723.T": "Renesas Electronics Corporation",
  "3092.T": "ZOZO, Inc.",
  "5831.T": "Shizuoka Financial Group,Inc.",
  "4661.T": "Oriental Land Co., Ltd.",
  "1802.T": "Obayashi Corporation",
  "4911.T": "Shiseido Company, Limited",
  "5801.T": "Furukawa Electric Co., Ltd.",
  "2282.T": "NH Foods Ltd.",
  "5706.T": "Mitsui Kinzoku Company, Limited",
  "8252.T": "Marui Group Co., Ltd.",
  "2503.T": "Kirin Holdings Company, Limited",
  "9201.T": "Japan Airlines Co., Ltd.",
  "7912.T": "Dai Nippon Printing Co., Ltd.",
  "6504.T": "Fuji Electric Co., Ltd.",
  "6113.T": "Amada Co., Ltd.",
  "6326.T": "Kubota Corporation",
  "7270.T": "Subaru Corporation",
  "1812.T": "Kajima Corporation",
  "8331.T": "The Chiba Bank, Ltd.",
  "5019.T": "Idemitsu Kosan Co.,Ltd.",
  "1801.T": "Taisei Corporation",
  "9107.T": "Kawasaki Kisen Kaisha, Ltd.",
  "4151.T": "Kyowa Kirin Co., Ltd.",
  "6178.T": "Japan Post Holdings Co., Ltd.",
  "1803.T": "Shimizu Corporation",
  "6701.T": "NEC Corporation",
  "8233.T": "Takashimaya Company, Limited",
  "7911.T": "TOPPAN Holdings Inc.",
  "1963.T": "JGC Holdings Corporation",
  "9434.T": "SoftBank Corp.",
  "6473.T": "JTEKT Corporation",
  "6770.T": "Alps Alpine Co., Ltd.",
  "2871.T": "Nichirei Corporation",
  "9064.T": "Yamato Holdings Co., Ltd.",
  "8316.T": "Sumitomo Mitsui Financial Group, Inc.",
  "2002.T": "Nisshin Seifun Group Inc.",
  "2501.T": "Sapporo Breweries Limited",
  "9022.T": "Central Japan Railway Company",
  "7013.T": "IHI Corporation",
  "6103.T": "Okuma Corporation",
  "9009.T": "Keisei Electric Railway Co., Ltd.",
  "6526.T": "Socionext Inc.",
  "7731.T": "Nikon Corporation",
  "3405.T": "Kuraray Co., Ltd.",
  "7186.T": "Yokohama Financial Group, Inc.",
  "9101.T": "Nippon Yusen Kabushiki Kaisha",
  "8601.T": "Daiwa Securities Group Inc.",
  "9104.T": "Mitsui O.S.K. Lines, Ltd.",
  "3407.T": "Asahi Kasei Corporation",
  "8804.T": "Tokyo Tatemono Co., Ltd.",
  "5714.T": "Dowa Holdings Co., Ltd.",
  "5214.T": "Nippon Electric Glass Co., Ltd.",
  "9147.T": "Nippon Express Holdings, Inc.",
  "7752.T": "Ricoh Company, Ltd.",
  "5301.T": "Tokai Carbon Co., Ltd.",
  "9432.T": "NTT, Inc.",
  "8604.T": "Nomura Holdings, Inc.",
  "2269.T": "Meiji Holdings Co., Ltd.",
  "5631.T": "The Japan Steel Works, Ltd.",
  "3086.T": "J. Front Retailing Co., Ltd.",
  "8354.T": "Fukuoka Financial Group, Inc.",
  "1605.T": "Inpex Corporation",
  "7012.T": "Kawasaki Heavy Industries, Ltd.",
  "4004.T": "Resonac Holdings Corporation",
  "4042.T": "Tosoh Corporation",
  "3289.T": "Tokyu Fudosan Holdings Corporation",
  "5020.T": "ENEOS Holdings, Inc.",
  "8309.T": "Sumitomo Mitsui Trust Group, Inc.",
  "1332.T": "Nissui Corporation",
  "4506.T": "Sumitomo Pharma Co., Ltd.",
  "9531.T": "Tokyo Gas Co.,Ltd.",
  "5201.T": "AGC Inc.",
  "7202.T": "Isuzu Motors Limited",
  "4751.T": "CyberAgent, Inc.",
  "3402.T": "Toray Industries, Inc.",
  "6471.T": "NSK Ltd.",
  "9020.T": "East Japan Railway Company",
  "9532.T": "Osaka Gas Co., Ltd.",
  "6302.T": "Sumitomo Heavy Industries, Ltd.",
  "8795.T": "T&D Holdings, Inc.",
  "7532.T": "Pan Pacific International Holdings Corporation",
  "9007.T": "Odakyu Electric Railway Co., Ltd.",
  "3861.T": "Oji Holdings Corporation",
  "3697.T": "SHIFT Inc.",
  "9005.T": "Tokyu Corporation",
  "4183.T": "Mitsui Chemicals, Inc.",
  "4755.T": "Rakuten Group, Inc.",
  "8411.T": "Mizuho Financial Group, Inc.",
  "9008.T": "Keio Corporation",
  "8750.T": "Daiichi Life Group, Inc.",
  "9602.T": "Toho Co., Ltd.",
  "4043.T": "Tokuyama Corporation",
  "2432.T": "DeNA Co., Ltd.",
  "4061.T": "Denka Company Limited",
  "9001.T": "Tobu Railway Co., Ltd.",
  "6753.T": "Sharp Corporation",
  "9021.T": "West Japan Railway Company",
  "4188.T": "Mitsubishi Chemical Group Corporation",
  "4902.T": "Konica Minolta, Inc.",
  "1808.T": "HASEKO Corporation",
  "2768.T": "Sojitz Corporation",
  "4005.T": "Sumitomo Chemical Company, Limited",
  "5711.T": "Mitsubishi Materials Corporation",
  "5233.T": "Taiheiyo Cement Corporation",
  "6472.T": "NTN Corporation",
  "3436.T": "Sumco Corporation",
  "7201.T": "Nissan Motor Co., Ltd.",
  "3401.T": "Teijin Limited",
  "5401.T": "Nippon Steel Corporation",
  "4208.T": "UBE Corporation",
  "9202.T": "ANA Holdings Inc.",
  "8304.T": "Aozora Bank, Ltd.",
  "9502.T": "Chubu Electric Power Company, Incorporated",
  "543A.T": "ARCHION Corporation",
  "9503.T": "The Kansai Electric Power Company, Incorporated",
  "7004.T": "Kanadevia Corporation",
  "7261.T": "Mazda Motor Corporation",
  "8308.T": "Resona Holdings, Inc.",
  "5406.T": "Kobe Steel, Ltd.",
  "5411.T": "JFE Holdings, Inc.",
  "4689.T": "LY Corporation",
  "9501.T": "Tokyo Electric Power Company Holdings, Incorporated",
  "7211.T": "Mitsubishi Motors Corporation",

  // ── Hang Seng ───────────────────────────────────────────────────
  "0005.HK": "HSBC Holdings plc",
  "0700.HK": "Tencent Holdings Limited",
  "9988.HK": "Alibaba Group Holding Limited",
  "1299.HK": "AIA Group Limited",
  "0939.HK": "China Construction Bank Corporation",
  "1398.HK": "Industrial and Commercial Bank of China Limited",
  "1810.HK": "Xiaomi Corporation",
  "0941.HK": "China Mobile Limited",
  "0388.HK": "Hong Kong Exchanges and Clearing Limited",
  "3690.HK": "Meituan",
  "0883.HK": "CNOOC Limited",
  "2318.HK": "Ping An Insurance (Group) Company of China, Ltd.",
  "3988.HK": "Bank of China Limited",
  "1211.HK": "BYD Company Limited",
  "0981.HK": "Semiconductor Manufacturing International Corporation",
  "9999.HK": "NetEase, Inc.",
  "0857.HK": "PetroChina Company Limited",
  "6160.HK": "BeOne Medicines AG",
  "2628.HK": "China Life Insurance Company Limited",
  "9618.HK": "JD.com, Inc.",
  "9888.HK": "Baidu, Inc.",
  "0016.HK": "Sun Hung Kai Properties Limited",
  "2899.HK": "Zijin Mining Group Company Limited",
  "0001.HK": "CK Hutchison Holdings Limited",
  "3968.HK": "China Merchants Bank Co., Ltd.",
  "2388.HK": "BOC Hong Kong (Holdings) Limited",
  "0669.HK": "Techtronic Industries Company Limited",
  "1024.HK": "Kuaishou Technology",
  "1088.HK": "China Shenhua Energy Company Limited",
  "3750.HK": "Contemporary Amperex Technology Co., Limited",
  "0175.HK": "Geely Automobile Holdings Limited",
  "1801.HK": "Innovent Biologics, Inc.",
  "2269.HK": "WuXi Biologics (Cayman) Inc.",
  "0002.HK": "CLP Holdings Limited",
  "1109.HK": "China Resources Land Limited",
  "9992.HK": "Pop Mart International Group Limited",
  "1378.HK": "China Hongqiao Group Limited",
  "2020.HK": "ANTA Sports Products Limited",
  "0823.HK": "Link Real Estate Investment Trust",
  "9961.HK": "Trip.com Group Limited",
  "0386.HK": "China Petroleum & Chemical Corporation",
  "1113.HK": "CK Asset Holdings Limited",
  "0006.HK": "Power Assets Holdings Limited",
  "0992.HK": "Lenovo Group Limited",
  "9633.HK": "Nongfu Spring Co., Ltd.",
  "2015.HK": "Li Auto Inc.",
  "0003.HK": "The Hong Kong and China Gas Company Limited",
  "0288.HK": "WH Group Limited",
  "0267.HK": "CITIC Limited",
  "0728.HK": "China Telecom Corporation Limited",
  "2057.HK": "ZTO Express (Cayman) Inc.",
  "0027.HK": "Galaxy Entertainment Group Limited",
  "3993.HK": "CMOC Group Limited",
  "0066.HK": "MTR Corporation Limited",
  "2359.HK": "WuXi AppTec Co., Ltd.",
  "0688.HK": "China Overseas Land & Investment Limited",
  "1093.HK": "CSPC Pharmaceutical Group Limited",
  "0300.HK": "Midea Group Co., Ltd.",
  "1177.HK": "Sino Biopharmaceutical Limited",
  "2319.HK": "China Mengniu Dairy Company Limited",
  "1519.HK": "J&T Global Express Limited",
  "3692.HK": "Hansoh Pharmaceutical Group Company Limited",
  "6690.HK": "Haier Smart Home Co., Ltd.",
  "0012.HK": "Henderson Land Development Company Limited",
  "0762.HK": "China Unicom (Hong Kong) Limited",
  "2688.HK": "ENN Energy Holdings Limited",
  "6618.HK": "JD Health International Inc.",
  "2382.HK": "Sunny Optical Technology (Group) Company Limited",
  "0291.HK": "China Resources Beer (Holdings) Company Limited",
  "0836.HK": "China Resources Power Holdings Company Limited",
  "1038.HK": "CK Infrastructure Holdings Limited",
  "1997.HK": "Wharf Real Estate Investment Company Limited",
  "2331.HK": "Li Ning Company Limited",
  "2600.HK": "Aluminum Corporation of China Limited",
  "1928.HK": "Sands China Ltd.",
  "2313.HK": "Shenzhou International Group Holdings Limited",
  "2618.HK": "JD Logistics, Inc.",
  "6181.HK": "Laopu Gold Co., Ltd.",
  "1209.HK": "China Resources Mixc Lifestyle Services Limited",
  "9901.HK": "New Oriental Education & Technology Group Inc.",
  "6862.HK": "Haidilao International Holding Ltd.",
  "0241.HK": "Alibaba Health Information Technology Limited",
  "1099.HK": "Sinopharm Group Co. Ltd.",
  "0322.HK": "Tingyi (Cayman Islands) Holding Corp.",
  "0868.HK": "Xinyi Glass Holdings Limited",
  "1929.HK": "Chow Tai Fook Jewellery Group Limited",
  "0285.HK": "BYD Electronic (International) Company Limited",
  "0960.HK": "Longfor Group Holdings Limited",
  "0316.HK": "Orient Overseas (International) Limited",
  "1044.HK": "Hengan International Group Company Limited",
  "0101.HK": "Hang Lung Properties Limited",
  "1876.HK": "Budweiser Brewing Company APAC Limited",
  "0968.HK": "Xinyi Solar Holdings Limited",

  // ── KOSPI ───────────────────────────────────────────────────────
  "005930.KS": "Samsung Electronics Co., Ltd.",
  "000660.KS": "SK hynix Inc.",
  "402340.KS": "SK Square Co., Ltd.",
  "009150.KS": "Samsung Electro-Mechanics Co., Ltd.",
  "005380.KS": "Hyundai Motor Company",
  "373220.KS": "LG Energy Solution, Ltd.",
  "207940.KS": "Samsung Biologics Co.,Ltd.",
  "012450.KS": "Hanwha Aerospace Co., Ltd.",
  "105560.KS": "KB Financial Group Inc.",
  "028260.KS": "Samsung C&T Corporation",
  "000270.KS": "Kia Corporation",
  "032830.KS": "Samsung Life Insurance Co., Ltd.",
  "329180.KS": "HD Hyundai Heavy Industries Co., Ltd.",
  "034020.KS": "Doosan Enerbility Co., Ltd.",
  "055550.KS": "Shinhan Financial Group Co., Ltd.",
  "068270.KS": "Celltrion, Inc.",
  "012330.KS": "Hyundai Mobis Co.,Ltd",
  "066570.KS": "LG Electronics Inc.",
  "086790.KS": "Hana Financial Group Inc.",
  "035420.KS": "NAVER Corporation",
  "010120.KS": "LS ELECTRIC Co., Ltd.",
  "034730.KS": "SK Inc.",
  "267260.KS": "HD Hyundai Electric Co., Ltd.",
  "298040.KS": "Hyosung Heavy Industries Corporation",
  "042660.KS": "Hanwha Ocean Co., Ltd.",
  "000810.KS": "Samsung Fire & Marine Insurance Co., Ltd.",
  "009540.KS": "HD Korea Shipbuilding & Offshore Engineering Co., Ltd.",
  "010130.KS": "Korea Zinc Company, Ltd.",
  "316140.KS": "Woori Financial Group Inc.",
  "005490.KS": "POSCO Holdings Inc.",
  "000150.KS": "Doosan Corporation",
  "051910.KS": "LG Chem, Ltd.",
  "042700.KS": "HANMI Semiconductor Co., Ltd.",
  "015760.KS": "Korea Electric Power Corporation",
  "017670.KS": "SK Telecom Co., Ltd.",
  "011200.KS": "HMM Co.,Ltd",
  "138040.KS": "Meritz Financial Group Inc.",
  "010140.KS": "Samsung Heavy Industries Co., Ltd.",
  "018260.KS": "Samsung SDS Co., Ltd.",
  "079550.KS": "LIG Defense&Aerospace Co., Ltd.",
  "033780.KS": "KT&G Corporation",
  "035720.KS": "Kakao Corp.",
  "003550.KS": "LG Corp.",
  "010950.KS": "S-Oil Corporation",
  "006400.KS": "Samsung SDI Co., Ltd.",
  "267250.KS": "HD Hyundai Co., Ltd.",
  "064350.KS": "Hyundai Rotem Company",
  "024110.KS": "Industrial Bank of Korea",
  "086280.KS": "Hyundai Glovis Co., Ltd.",
  "278470.KS": "APR Co., Ltd.",
  "272210.KS": "Hanwha Systems Co., Ltd.",
  "003670.KS": "Posco Future M Co., Ltd.",
  "047810.KS": "Korea Aerospace Industries, Ltd.",
  "011070.KS": "LG Innotek Co., Ltd.",
  "030200.KS": "KT Corporation",
  "000720.KS": "Hyundai Engineering & Construction Co.,Ltd.",
  "307950.KS": "Hyundai Autoever Corporation",
  "071050.KS": "Korea Investment Holdings Co., Ltd.",
  "096770.KS": "SK Innovation Co., Ltd.",
  "005940.KS": "NH Investment & Securities Co., Ltd.",
  "259960.KS": "KRAFTON, Inc.",
  "323410.KS": "KakaoBank Corp.",
  "078930.KS": "GS Holdings Corp.",
  "005830.KS": "DB Insurance Co., Ltd.",
  "028050.KS": "Samsung E&A Co., Ltd.",
  "090430.KS": "Amorepacific Corporation",
  "047050.KS": "Posco International Corporation",
  "003230.KS": "Samyang Foods Co., Ltd.",
  "006260.KS": "LS Corp.",
  "443060.KS": "HD Hyundai Marine Solution CO.,LTD.",
  "161390.KS": "Hankook Tire & Technology Co., Ltd.",
  "016360.KS": "Samsung Securities Co.,Ltd.",
  "009830.KS": "Hanwha Solutions Corporation",
  "180640.KS": "Hanjin Kal",
  "003490.KS": "Korean Airlines Co.,Ltd.",
  "006800.KS": "Mirae Asset Securities Co., Ltd.",
  "039490.KS": "Kiwoom Securities Co., Ltd.",
  "064400.KS": "LG CNS",
  "047040.KS": "Daewoo Engineering & Construction Co., Ltd.",
  "352820.KS": "HYBE Co., Ltd.",
  "000880.KS": "Hanwha Corporation",
  "007660.KS": "ISU Petasys Co., Ltd.",
  "326030.KS": "SK Biopharmaceuticals Co., Ltd.",
  "021240.KS": "COWAY Co., Ltd.",
  "032640.KS": "LG Uplus Corp.",
  "241560.KS": "Doosan Bobcat Inc.",
  "000100.KS": "Yuhan Corporation",
  "377300.KS": "Kakao Pay Corp.",
  "353200.KS": "DAEDUCK ELECTRONICS Co., Ltd.",
  "062040.KS": "SANIL ELECTRIC",
  "001440.KS": "Taihan Cable & Solution Co., Ltd.",
  "271560.KS": "ORION Corp.",
  "454910.KS": "Doosan Robotics Inc.",
  "029780.KS": "Samsung Card Co., Ltd.",
  "034220.KS": "LG Display Co., Ltd.",
  "036570.KS": "NC Corporation",
  "001040.KS": "CJ Corporation",
  "011790.KS": "SKC Co., Ltd.",
  "000990.KS": "DB HiTek CO., LTD.",
  "082740.KS": "Hanwha Engine Co., Ltd.",
  "018880.KS": "Hanon Systems",
  "052690.KS": "KEPCO Engineering & Construction Company, Inc.",
  "004170.KS": "SHINSEGAE Inc.",
  "103590.KS": "Iljin Electric Co.,Ltd",
  "002380.KS": "KCC Corporation",
  "011780.KS": "Kumho Petro Chemical Co.,Ltd",
  "251270.KS": "Netmarble Corporation",
  "036460.KS": "Korea Gas Corporation",
  "028670.KS": "Pan Ocean Co., Ltd.",
  "336260.KS": "Doosan Fuel Cell Co., Ltd.",
  "008930.KS": "Hanmi Science Co., Ltd.",
  "097950.KS": "CJ Cheiljedang Corporation",
  "035250.KS": "Kangwon Land, Inc.",
  "023530.KS": "Lotte Shopping Co., Ltd.",
  "450080.KS": "ECOPRO MAT",
  "014680.KS": "Hansol Chemical Co., Ltd.",
  "383220.KS": "F&F Co., Ltd",
  "010060.KS": "OCI Holdings Company Ltd.",
  "282330.KS": "BGF Retail Co., Ltd.",
  "011170.KS": "Lotte Chemical Corporation",
  "073240.KS": "Kumho Tire Co., Inc.",
  "004370.KS": "Nongshim Co., Ltd.",
  "081660.KS": "Misto Holdings Corp.",
  "181710.KS": "NHN Corporation",
  "030000.KS": "Cheil Worldwide Inc.",
  "051900.KS": "LG H&H Co., Ltd.",
  "004990.KS": "LOTTE Corporation",
  "462870.KS": "SHIFT UP",
  "000120.KS": "CJ Logistics Corporation",
  "020560.KS": "Asiana Airlines, Inc.",
  "192080.KS": "DoubleUGames Co., Ltd.",
  "007310.KS": "Otoki Corporation",
  "000080.KS": "HITEJINRO Co., Ltd.",
  "079160.KS": "CJ CGV Co., Ltd.",
  "137310.KS": "SD Biosensor, Inc.",
  "002350.KS": "Nexen Tire Corporation",
  "003620.KS": "KG Mobility Corp.",
  "019170.KS": "Shinpoong Pharmaceutical Co.,Ltd",
  "089590.KS": "Jeju Air Co., Ltd.",
  "272450.KS": "Jin Air Co., Ltd.",
  "091810.KS": "Trinity Airways Co., Ltd.",
  "279570.KS": "Kbank",
  "217590.KS": "TMC",
  "317450.KS": "MYUNGIN PHARM",
  "439260.KS": "Daehan Shipbuilding Co., Ltd.",
  "483650.KS": "d'Alba Global",
  "480370.KS": "씨케이솔루션",
  "031210.KS": "Seoul Guarantee Insurance Company",
  "499790.KS": "GS P&L",
  "484870.KS": "MNC Solution",
  "415640.KS": "KB Balhae Infrastructure Fund",
  "475560.KS": "The BORN Korea",
  "489790.KS": "Hanwha Vision CO.,LTD",
  "079900.KS": "Junjin Construction & Robot Co.,Ltd.",
  "487570.KS": "HS HYOSUNG Corporation",
  "481850.KS": "Shinhan Global Active REIT Co., Ltd.",
  "034230.KS": "Paradise Co., Ltd.",
  "475150.KS": "SK eternix Co., Ltd.",
  "066970.KS": "L&F",
  "022100.KS": "Posco Dx Company Ltd.",
  "017860.KS": "DS DANSUK CO., LTD.",
  "111380.KS": "DONG IN ENTECH",
  "465770.KS": "STX Green Logis Ltd",
  "092790.KS": "NEXTEEL Co., Ltd.",
  "030190.KS": "NICE Information Service Co., Ltd.",
  "462520.KS": "Chosun Refractories Co.,Ltd.",
  "090460.KS": "BH Co., Ltd.",
  "460850.KS": "Dongkuk CM Co., Ltd.",
  "460860.KS": "Dongkuk Steel Mill Company Limited",
  "457190.KS": "이수스페셜티케미컬",
  "456040.KS": "OCI Company Ltd.",
  "100090.KS": "SK oceanplant Co.,Ltd",
  "448730.KS": "Samsung FN REIT Co., Ltd.",
  "453340.KS": "Hyundai Green Food Co., Ltd",
  "452260.KS": "Hanwha Galleria Corporation",
  "451800.KS": "Hanwha REIT Co., Ltd.",
  "377740.KS": "BioNote, Inc.",
  "446070.KS": "유니드비티플러스",
  "108320.KS": "LX Semicon Co., Ltd.",
  "432320.KS": "KB STAR REIT Co., Ltd.",
  "403550.KS": "SOCAR Inc.",
  "126720.KS": "Soosan Industries Co., Ltd.",
  "357430.KS": "MASTERN PREMIER REIT 1 Co., Ltd.",
  "417310.KS": "Koramco The One REIT",
  "404990.KS": "Shinhan Seobu T&D REIT Co., Ltd.",
  "396690.KS": "Mirae Asset Global REIT Co., Ltd.",
  "400760.KS": "NH All-One REIT Co., Ltd.",
  "381970.KS": "K Car Co., Ltd.",
  "395400.KS": "SK Reits Co., Ltd.",
  "271940.KS": "Iljin Hysolus Co., Ltd.",
  "377190.KS": "D&D platform REIT Co., Ltd.",
  "139990.KS": "AJUSTEEL Co.,Ltd",
  "089860.KS": "LOTTE rental co.,ltd.",
  "372910.KS": "Hancom Lifecare Inc.",
  "178920.KS": "PI Advanced Materials Co., Ltd.",
  "097520.KS": "MCNEX Co., Ltd",
  "383800.KS": "LX Holdings Corp.",
  "361610.KS": "SK IE Technology Co., Ltd.",
  "302440.KS": "SK bioscience Co.,Ltd.",
  "378850.KS": "Hwaseung R&A Co., Ltd.",
  "950210.KS": "Prestige BioPharma Limited",
  "248070.KS": "Solum Co., Ltd.",
  "375500.KS": "DL E&C Co.,Ltd.",
  "365550.KS": "ESR Kendall Square REIT Co., Ltd.",
  "009900.KS": "Myoung Shin Industrial Co.,Ltd",
  "244920.KS": "Aplus Asset Advisor Co. Ltd",
  "339770.KS": "Kyochon Food&Beverage Co., Ltd.",
  "363280.KS": "TY Holdings Co., Ltd",
  "357120.KS": "Koramco Life Infra Reit",
  "348950.KS": "JR Global REIT",
  "357250.KS": "Miraeasset Maps REIT 1 Co., Ltd.",
  "350520.KS": "IGIS RESIDENCE REIT Co., Ltd.",
  "334890.KS": "IGIS Value Plus REIT Co., Ltd.",
  "344820.KS": "KCC GLASS Corporation",
  "338100.KS": "NH Prime REIT Co., Ltd.",
  "308170.KS": "CTR Mobility Co.,Ltd.",
  "322000.KS": "HD Hyundai Energy Solutions Co.,Ltd.",
  "317400.KS": "Xi S&D Inc.",
  "330590.KS": "LOTTE REIT Co., Ltd.",
  "013890.KS": "Zinus, Inc",
  "336370.KS": "Solus Advanced Materials Co., Ltd.",
  "036420.KS": "ContentreeJoongAng corp.",
  "192650.KS": "DREAMTECH Co., Ltd.",
  "267850.KS": "Asiana IDT, Inc.",
  "306200.KS": "SeAH Steel Corporation",
  "293480.KS": "Hana Pharm Co., Ltd.",
  "010400.KS": "Woojin I&S Co., Ltd.",
  "293940.KS": "Shinhan Alpha REIT Co., Ltd.",
  "300720.KS": "Hanil Cement Co., Ltd.",
  "286940.KS": "LOTTE INNOVATE Co.,Ltd",
  "298050.KS": "HS Hyosung Advanced Materials Corporation",
  "298020.KS": "Hyosung TNC Corporation",
  "298000.KS": "Hyosung Chemical Corporation",
  "088260.KS": "E Kocref Cr-Reit",
  "294870.KS": "IPARK Hyundai Development Company",
  "018250.KS": "Aekyung Industrial Co., Ltd.",
  "284740.KS": "CUCKOO Homesys Co., Ltd",
  "285130.KS": "SK Chemicals Co.,Ltd",
  "092780.KS": "DYP Co.,Ltd",
  "281820.KS": "KCTech Co., Ltd.",
  "272550.KS": "Samyang Packaging Corporation",
  "055490.KS": "Tapex Co., Ltd.",
  "280360.KS": "Lotte Wellfood Co.,Ltd",
  "271980.KS": "Jeil Pharmaceutical Co.,Ltd",
  "268280.KS": "Miwon Specialty Chemical Co., Ltd.",
  "267290.KS": "Kyungdong City Gas Co., Ltd",
  "267270.KS": "HD Construction Equipment Co., Ltd.",
  "264900.KS": "Crown Confectionery Co., Ltd.",
  "145720.KS": "Dentium CO., LTD",
  "111110.KS": "Hojeon Limited",

  // ── TAIEX ───────────────────────────────────────────────────────
  "2330.TW": "Taiwan Semiconductor Manufacturing Company Limited",
  "2454.TW": "MediaTek Inc.",
  "2308.TW": "Delta Electronics, Inc.",
  "2317.TW": "Hon Hai Precision Industry Co., Ltd.",
  "3711.TW": "ASE Technology Holding Co., Ltd.",
  "2881.TW": "Fubon Financial Holding Co., Ltd.",
  "2383.TW": "Elite Material Co., Ltd.",
  "2408.TW": "Nanya Technology Corporation",
  "2303.TW": "United Microelectronics Corporation",
  "2882.TW": "Cathay Financial Holding Co., Ltd.",
  "1303.TW": "Nan Ya Plastics Corporation",
  "3037.TW": "Unimicron Technology Corp.",
  "2327.TW": "Yageo Corporation",
  "6949.TW": "Pell Bio-Med Technology Co., Ltd.",
  "2891.TW": "CTBC Financial Holding Co., Ltd.",
  "2345.TW": "Accton Technology Corporation",
  "3017.TW": "Asia Vital Components Co., Ltd.",
  "2382.TW": "Quanta Computer Inc.",
  "7769.TW": "Hon. Precision, Inc.",
  "2059.TW": "King Slide Works Co., Ltd.",
  "6669.TW": "Wiwynn Corporation",
  "2412.TW": "Chunghwa Telecom Co., Ltd.",
  "2360.TW": "Chroma ATE Inc.",
  "2885.TW": "Yuanta Financial Holding Co., Ltd.",
  "2887.TW": "TS Financial Holding Co., Ltd.",
  "2344.TW": "Winbond Electronics Corporation",
  "8046.TW": "Nan Ya Printed Circuit Board Corporation",
  "3443.TW": "Global Unichip Corp.",
  "2357.TW": "ASUSTeK Computer Inc.",
  "2886.TW": "Mega Financial Holding Co., Ltd.",
  "3653.TW": "Jentech Precision Industrial Co., Ltd",
  "6505.TW": "Formosa Petrochemical Corporation",
  "3231.TW": "Wistron Corporation",
  "2301.TW": "Lite-On Technology Corporation",
  "6446.TW": "PharmaEssentia Corporation",
  "3008.TW": "Largan Precision Co., Ltd.",
  "2395.TW": "Advantech Co., Ltd.",
  "2884.TW": "E.SUN Financial Holding Company, Ltd.",
  "2890.TW": "SinoPac Financial Holdings Company Limited",
  "2880.TW": "Hua Nan Financial Holdings Co., Ltd.",
  "2883.TW": "KGI Financial Holding Co., Ltd.",
  "4958.TW": "Zhen Ding Technology Holding Limited",
  "2368.TW": "Gold Circuit Electronics Ltd.",
  "2892.TW": "First Financial Holding Co., Ltd.",
  "2603.TW": "Evergreen Marine Corporation (Taiwan) Ltd.",
  "3189.TW": "Kinsus Interconnect Technology Corp.",
  "1216.TW": "Uni-President Enterprises Corp.",
  "3665.TW": "BizLink Holding Inc.",
  "3045.TW": "Taiwan Mobile Co., Ltd.",
  "3481.TW": "Innolux Corporation",
  "2379.TW": "Realtek Semiconductor Corp.",
  "5880.TW": "Taiwan Cooperative Financial Holding Co., Ltd.",
  "1301.TW": "Formosa Plastics Corporation",
  "3661.TW": "Alchip Technologies, Limited",
  "4904.TW": "Far EasTone Telecommunications Co., Ltd.",
  "6770.TW": "Powerchip Semiconductor Manufacturing Corporation",
  "1326.TW": "Formosa Chemicals & Fibre Corporation",
  "3034.TW": "Novatek Microelectronics Corp.",
  "2449.TW": "King Yuan Electronics Co., Ltd.",
  "2002.TW": "China Steel Corporation",
  "1590.TW": "Airtac International Group",
  "2207.TW": "Hotai Motor Co.,Ltd.",
  "2801.TW": "Chang Hwa Commercial Bank, Ltd.",
  "3036.TW": "WT Microelectronics Co., Ltd.",
  "2337.TW": "Macronix International Co., Ltd.",
  "2376.TW": "Giga-Byte Technology Co., Ltd.",
  "2313.TW": "Compeq Manufacturing Co., Ltd.",
  "3044.TW": "Tripod Technology Corporation",
  "4938.TW": "Pegatron Corporation",
  "2356.TW": "Inventec Corporation",
  "2615.TW": "Wan Hai Lines Ltd.",
  "6515.TW": "WinWay Technology Co., Ltd.",
  "1519.TW": "Fortune Electric Co., Ltd.",
  "2912.TW": "President Chain Store Corporation",
  "2618.TW": "EVA Airways Corp.",
  "2404.TW": "United Integrated Services Co., Ltd.",
  "6239.TW": "Powertech Technology Inc.",
  "3702.TW": "WPG Holdings Limited",
  "5876.TW": "The Shanghai Commercial & Savings Bank, Ltd.",
  "3533.TW": "Lotes Co., Ltd.",
  "5871.TW": "Chailease Holding Company Limited",
  "2409.TW": "AUO Corporation",
  "6139.TW": "L&K Engineering Co., Ltd.",
  "6415.TW": "Silergy Corp.",
  "1101.TW": "TCC Group Holdings Co., Ltd.",
  "2609.TW": "Yang Ming Marine Transport Corporation",
  "1605.TW": "Walsin Lihwa Corporation",
  "2324.TW": "Compal Electronics, Inc.",
  "6213.TW": "ITEQ Corporation",
  "7750.TW": "Syntec Technology Co., Ltd.",
  "1504.TW": "TECO Electric & Machinery Co., Ltd.",
  "1802.TW": "Taiwan Glass Ind. Corp.",
  "6919.TW": "CALIWAY BIOPHARMACEUTICALS CO L",
  "2834.TW": "Taiwan Business Bank, Ltd.",
  "2492.TW": "Walsin Technology Corporation",
  "2347.TW": "Synnex Technology International Corporation",
  "910322.TW": "Tingyi (Cayman Islands) Holding Corp.",
  "2633.TW": "Taiwan High Speed Rail Corporation",
  "1402.TW": "Far Eastern New Century Corporation",
  "6789.TW": "VisEra Technologies Company Ltd.",
  "2377.TW": "Micro-Star International Co., Ltd.",
  "6531.TW": "AP Memory Technology Corporation",
  "2049.TW": "Hiwin Technologies Corporation",
  "3532.TW": "Formosa Sumco Technology Corporation",
  "2451.TW": "Transcend Information, Inc.",
  "2027.TW": "Ta Chen Stainless Pipe Co., Ltd.",
  "6442.TW": "EZconn Corporation",
  "6805.TW": "Fositek Corp.",
  "8210.TW": "Chenbro Micom Co., Ltd.",
  "2610.TW": "China Airlines, Ltd.",
  "3706.TW": "MiTAC Holdings Corporation",
  "8996.TW": "Kaori Heat Treatment Co., Ltd.",
  "6285.TW": "WNC Corporation",
  "3026.TW": "Holy Stone Enterprise Co.,Ltd.",
  "6196.TW": "Marketech International Corp.",
  "1102.TW": "Asia Cement Corporation",
  "2812.TW": "Taichung Commercial Bank Co., Ltd.",
  "2474.TW": "Catcher Technology Co., Ltd.",
  "8464.TW": "Nien Made Enterprise Co., LTD.",
  "5269.TW": "ASMedia Technology Inc.",
  "7610.TW": "LIANYOU METALS CO LTD",
  "1560.TW": "Kinik Company",
  "1503.TW": "Shihlin Electric & Engineering Corp.",
  "6526.TW": "Airoha Technology Corp.",
  "6257.TW": "Sigurd Microelectronics Corporation",
  "5434.TW": "Topco Scientific Co.,Ltd.",
  "2542.TW": "Highwealth Construction Corp.",
  "2105.TW": "Cheng Shin Rubber Ind. Co., Ltd.",
  "2353.TW": "Acer Incorporated",
  "6781.TW": "Advanced Energy Solution Holding Co., Ltd.",
  "1717.TW": "Eternal Materials Co., Ltd.",
  "1476.TW": "Eclat Textile Co., Ltd.",
  "2354.TW": "Foxconn Technology Co., Ltd.",
  "6691.TW": "Yankey Engineering Co., Ltd.",
  "2838.TW": "Union Bank of Taiwan",
  "9105.TW": "Cal-Comp Electronics (Thailand) Public Company Limited",
  "1513.TW": "Chung-Hsin Electric and Machinery Manufacturing Corp.",
  "2467.TW": "C Sun Mfg Ltd.",
  "6409.TW": "Voltronic Power Technology Corp.",
  "3006.TW": "Elite Semiconductor Microelectronics Technology Inc.",
  "2385.TW": "Chicony Electronics Co., Ltd.",
  "9945.TW": "Ruentex Development Co.,Ltd.",
  "3450.TW": "Elite Advanced Laser Corporation",
  "2855.TW": "President Securities Corporation",
  "3023.TW": "SINBON Electronics Co., Ltd.",
  "1229.TW": "Lien Hwa Industrial Holdings Corporation",
  "3030.TW": "Test Research, Inc.",
  "3005.TW": "Getac Holdings Corporation",
  "2441.TW": "Greatek Electronics Inc.",
  "2455.TW": "Visual Photonics Epitaxy Co., Ltd.",
  "3406.TW": "Genius Electronic Optical Co.,Ltd.",
  "8454.TW": "momo.com Inc.",
  "9904.TW": "Pou Chen Corporation",
  "9910.TW": "Feng Tay Enterprises Co., Ltd.",
  "2645.TW": "Evergreen Aviation Technologies Corporation",
  "6005.TW": "Capital Securities Corporation",
  "6414.TW": "Ennoconn Corporation",
  "8039.TW": "Taiflex Scientific Co., Ltd.",
  "8150.TW": "ChipMOS TECHNOLOGIES INC.",
  "2845.TW": "Far Eastern International Bank Ltd.",
  "3042.TW": "TXC Corporation",
  "2637.TW": "Wisdom Marine Lines Co., Limited (Cayman)",
  "2006.TW": "Tung Ho Steel Enterprise Corporation",
  "8021.TW": "Topoint Technology Co., Ltd.",
  "2646.TW": "STARLUX Airlines Co., Ltd.",
  "2634.TW": "Aerospace Industrial Development Corporation",
  "3167.TW": "Ta Liang Technology Co., Ltd.",
  "2915.TW": "Ruentex Industries Ltd.",
  "6944.TW": "Mega Union Technology Inc.",
  "3583.TW": "Scientech Corporation",
  "7799.TW": "Heron Neutron Medical Corp.",
  "2867.TW": "Mercuries Life Insurance Company Ltd.",
  "2889.TW": "IBF Financial Holdings Co., Ltd.",
  "2371.TW": "Tatung Co., Ltd.",
  "2258.TW": "FOXTRON VEHICLE TECHS CO LTD",
  "2606.TW": "U-Ming Marine Transport Corporation",
  "2481.TW": "PANJIT International Inc.",
  "2486.TW": "I-Chiun Precision Industry Co., Ltd.",
  "1477.TW": "Makalot Industrial Co., Ltd.",
  "6472.TW": "Bora Pharmaceuticals Co., Ltd.",
  "4919.TW": "Nuvoton Technology Corporation",
  "2597.TW": "Ruentex Engineering & Construction Co., Ltd.",
  "8112.TW": "Supreme Electronics Co., Ltd.",
  "4763.TW": "Jinan Acetate Chemical Co., Ltd.",
  "2850.TW": "Shinkong Insurance Co., Ltd.",
  "3090.TW": "Nichidenbo Corporation",
  "1795.TW": "Lotus Pharmaceutical Co., Ltd.",
  "6451.TW": "ShunSin Technology Holdings Limited",
  "2312.TW": "Kinpo Electronics, Inc.",
  "2539.TW": "Sakura Development Co.,Ltd",
  "1907.TW": "YFY Inc.",
  "9941.TW": "Taiwan Acceptance Corporation",
  "6278.TW": "Taiwan Surface Mounting Technology Corp.",
  "5522.TW": "Farglory Land Development Co., Ltd.",
  "9917.TW": "Taiwan Secom Co., Ltd.",
  "1773.TW": "Shiny Chemical Industrial Co., Ltd.",
  "8028.TW": "Phoenix Silicon International Corporation",
  "2923.TW": "Sino Horizon Holdings Limited",
  "2206.TW": "Sanyang Motor Co., Ltd.",
  "1210.TW": "Great Wall Enterprise Co., Ltd.",
  "1319.TW": "Tong Yang Industry Co., Ltd.",
  "8926.TW": "Taiwan Cogeneration Corporation",
  "3035.TW": "Faraday Technology Corporation",
  "6831.TW": "Taiwan Microloops Corp.",
  "2352.TW": "Qisda Corporation",
  "3563.TW": "Machvision Inc.",
  "1722.TW": "Taiwan Fertilizer Co., Ltd.",
  "6890.TW": "Lai Yih Footwear Co., Ltd.",
  "2458.TW": "ELAN Microelectronics Corporation",
  "7795.TW": "Eternal Precision Mechanics Co., Ltd.",
  "6191.TW": "Global Brands Manufacture Ltd.",
  "3714.TW": "ENNOSTAR Inc.",
  "2421.TW": "Sunonwealth Electric Machine Industry Co., Ltd.",
  "1736.TW": "Johnson Health Tech .Co., Ltd.",
  "6214.TW": "Systex Corporation",
  "2464.TW": "Mirle Automation Corporation",
  "2540.TW": "JSL Construction & Development Co., Ltd.",
  "2388.TW": "VIA Technologies, Inc.",
  "2472.TW": "Lelon Electronics Corp.",
  "6271.TW": "Tong Hsing Electronic Industries, Ltd.",
  "6282.TW": "AcBel Polytech Inc.",
  "9921.TW": "Giant Manufacturing Co., Ltd.",
  "4583.TW": "Apex Dynamics, Inc.",
  "4766.TW": "Nan Pao Resins Chemical Co., Ltd.",
  "1409.TW": "Shinkong Synthetic Fibers Corporation",
  "7822.TW": "V5 TECHNOLOGIES CO LTD",
  "9939.TW": "Taiwan Hon Chuan Enterprise Co., Ltd.",
  "6116.TW": "HannStar Display Corporation",
  "9933.TW": "CTCI Corporation",
  "3019.TW": "Asia Optical Co., Inc.",
  "6592.TW": "Hotai Finance Co., Ltd.",
  "6197.TW": "JPC Connectivity Inc.",
  "8016.TW": "Sitronix Technology Corporation",
  "5469.TW": "HannStar Board Corporation",
  "6670.TW": "FuSheng Precision Co., Ltd.",
  "3376.TW": "Shin Zu Shing Co., Ltd.",
  "2015.TW": "Feng Hsin Steel Co., Ltd.",
  "2504.TW": "Goldsun Building Materials Co., Ltd.",
  "3596.TW": "Arcadyan Technology Corporation",
  "8422.TW": "Cleanaway Company Limited",
  "2211.TW": "Evergreen Steel Corp.",
  "8070.TW": "Chang Wah Electromaterials Inc.",
  "7711.TW": "ASRock Rack Incorporation",
  "5234.TW": "Daxin Materials Corporation",
  "3010.TW": "Wah Lee Industrial Corporation",
  "2498.TW": "HTC Corporation",
  "2351.TW": "SDI Corporation",
  "3413.TW": "Foxsemicon Integrated Technology Inc.",
  "3715.TW": "Dynamic Holding Co., Ltd.",
  "2428.TW": "Thinking Electronic Industrial Co., Ltd.",
};

/**
 * Company name for a heatmap tile, or `null` when unknown.
 *
 * Prefer the constituent's `yahoo` symbol. `ticker` is accepted as a fallback
 * for any tile authored without one, but note it can be ambiguous across
 * indices — the symbol lookup is the correct one.
 */
export function getCompanyName(symbol: string, ticker?: string): string | null {
  return TICKER_NAMES[symbol] ?? (ticker ? TICKER_NAMES[ticker] ?? null : null);
}
