"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import dynamic from "next/dynamic";
import type { EChartsOption } from "echarts";
import { CHART_COLORS, useTheme } from "@/lib/use-theme";
import { ArrowRight, CarFront, RotateCcw } from "lucide-react";
import { DEFAULT_CAR, modelCar, validateCar, carBreakEvens, carScenarioCsv, type CarInputs } from "@/lib/car-model";

const ReactECharts = dynamic(() => import("echarts-for-react"), { ssr: false });

type Field = [keyof CarInputs, string, string, string];
const buyFields: Field[] = [
  ["price", "Purchase price", "$", "All-in price, including taxes and purchase fees."],
  ["down", "Down payment", "$", "Cash paid upfront toward the purchase."],
  ["rate", "Loan interest rate", "%", "Annual nominal rate, compounded monthly."],
  ["loanMonths", "Loan term", "months", "Full repayment period, independent of the lease term."],
  ["resale", "Resale value after your driving duration", "$", "Net sale proceeds after keeping the purchased car for your full driving duration. Consider its age and kilometres driven."]
];
const leaseFields: Field[] = [
  ["lease", "Monthly lease payment", "$/mo", "Use the quoted payment including applicable tax."],
  ["upfront", "Additional upfront lease costs", "$", "Non-refundable down payment and fees at the start of each lease. Exclude the first monthly payment; it is already counted."],
  ["leaseMonths", "Lease term", "months", "Length of each lease. Over a longer driving duration, repeat leases use these same quoted terms."],
  ["distance", "Expected annual kilometres · lease", "km/yr", "Used only to calculate lease excess-kilometre fees. Buying has no mileage limit."],
  ["allowance", "Lease annual km allowance", "km/yr", "Contractual allowance for leasing only. There is no allowance or excess-km charge when you buy."]
];
const advancedFields: Field[] = [
  ["buyRunning", "Buying: annual running costs", "$/yr", "Maintenance, insurance and other running costs."],
  ["leaseRunning", "Leasing: annual running costs", "$/yr", "Include the same categories as the buying path."],
  ["excessRate", "Excess mileage charge", "$/km", "Lease only: charge per kilometre above each lease’s allowance, including tax."],
  ["runningInflation", "Annual running-cost inflation", "%/yr", "Both running-cost budgets rise at each anniversary. Payments and return fees stay fixed."],
  ["returnFees", "Return costs per lease", "$", "Disposition fees and expected wear charges, including tax."]
];
export default function CarDecision() {
  const [inputs, setInputs] = useState({ ...DEFAULT_CAR });
  const [currency, setCurrency] = useState("CAD");
  const [chartView, setChartView] = useState<"wealth" | "cash">("wealth");
  const colors = CHART_COLORS[useTheme()];
  const error = validateCar(inputs);
  const result = useMemo(() => error ? null : modelCar(inputs), [inputs, error]);
  const thresholds = useMemo(() => error ? null : carBreakEvens(inputs), [inputs, error]);
  const money = (v: number) => new Intl.NumberFormat("en-CA", { style: "currency", currency, maximumFractionDigits: 0 }).format(v);
  const field = ([key, label, unit, hint]: Field) => <label key={key} className="block text-xs font-medium" htmlFor={`car-${key}`}>
    {label}<div className="mt-2 flex items-center rounded-lg border border-space-border bg-space-void focus-within:border-neon-cyan"><input id={`car-${key}`} type="number" min={key === "investmentReturn" ? -20 : ["months", "loanMonths", "leaseMonths"].includes(key) ? 1 : 0} max={key === "months" ? 360 : ["loanMonths", "leaseMonths"].includes(key) ? 120 : undefined} step={["rate", "excessRate", "investmentReturn", "runningInflation"].includes(key) ? 0.01 : 1} value={Number.isNaN(inputs[key]) ? "" : inputs[key]} onChange={e => setInputs(p => ({ ...p, [key]: e.target.value === "" ? NaN : Number(e.target.value) }))} className="w-full min-w-0 bg-transparent p-3 font-mono text-sm outline-none" /><span className="whitespace-nowrap pr-3 text-text-muted">{unit}</span></div><span className="mt-1.5 block text-[11px] font-normal leading-relaxed text-text-secondary">{hint}</span>
  </label>;
  const difference = result?.final.difference ?? 0;
  const chart: EChartsOption = {
    color: [colors.series1, colors.series2],
    tooltip: { trigger: "axis", backgroundColor: colors.tooltipBg, borderColor: colors.tooltipBorder, textStyle: { color: colors.tooltipText }, valueFormatter: value => money(Number(value)) },
    legend: { bottom: 0, textStyle: { color: colors.axisLabel } },
    grid: { left: 15, right: 15, top: 20, bottom: 55, containLabel: true },
    xAxis: { type: "category", data: result?.periods.map(p => chartView === "wealth" ? `Month ${p.month}` : `Months ${p.startMonth}–${p.month}`), axisLabel: { color: colors.axisLabel }, axisLine: { lineStyle: { color: colors.axisLine } } },
    yAxis: { type: "value", axisLabel: { color: colors.axisLabel, formatter: value => new Intl.NumberFormat("en", { notation: "compact" }).format(value) }, splitLine: { lineStyle: { color: colors.grid } } },
    series: ["Buy", "Lease"].map((name, index) => ({ name, type: chartView === "wealth" ? "line" : "bar", showSymbol: true, lineStyle: { width: 3 }, data: result?.periods.map(p => chartView === "wealth" ? (index === 0 ? p.buyWealth : p.leaseWealth) : (index === 0 ? p.buyCashOutflow : p.leaseCashOutflow)) })),
  };
  function downloadCsv() {
    if (!result) return;
    const url = URL.createObjectURL(new Blob([carScenarioCsv(inputs, currency)], { type: "text/csv;charset=utf-8" }));
    const link = document.createElement("a"); link.href = url; link.download = "car-buy-vs-lease.csv";
    document.body.appendChild(link); link.click(); link.remove();
    window.setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
  return <div className="section-shell py-8 sm:py-12">
    <Link href="/decisions" className="inline-flex text-sm text-text-secondary hover:text-neon-cyan">← All comparisons</Link>
    <header className="mb-8 mt-7 flex flex-wrap items-end justify-between gap-5 border-b border-space-border pb-7">
      <div><p className="text-xs uppercase tracking-widest text-neon-cyan">Decision Studio / Car</p><h1 className="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">Own the car. Or lease it.</h1><p className="mt-3 max-w-xl text-sm leading-relaxed text-text-secondary">The monthly payment is only the beginning. Choose how long you will drive. Compare keeping one purchased car with leasing over that same period, including your car’s remaining value and the savings you could invest.</p></div>
      <label className="text-xs font-semibold">Currency<select value={currency} onChange={e => setCurrency(e.target.value)} className="mt-2 block rounded-lg border border-space-border bg-space-card px-4 py-2 text-sm">{["CAD", "USD", "EUR", "GBP", "INR", "AUD"].map(c => <option key={c}>{c}</option>)}</select><span className="mt-1 block text-[11px] font-normal text-text-muted">Labels only; no conversion.</span></label>
    </header>
    <div className="grid items-start gap-6 lg:grid-cols-[360px_minmax(0,1fr)]">
      <aside className="order-2 overflow-hidden rounded-2xl lg:order-1 border border-space-border bg-space-card">
        <div className="border-b border-space-border p-6"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 font-semibold"><CarFront size={18} /> Your comparison</h2><button type="button" aria-label="Reset car assumptions" onClick={() => setInputs({ ...DEFAULT_CAR })} className="rounded-full p-2 hover:bg-space-void"><RotateCcw size={15} /></button></div><p className="mt-2 text-xs leading-relaxed text-text-secondary">Example numbers to get started. Replace them with quotes for the same car.</p><div className="mt-5 space-y-4">{field(["months", "How long will you drive the car?", "months", "Keep the bought car for this duration (up to 30 years). Independent of loan and lease terms. Choose complete lease terms for a fair comparison."])}<div className="flex flex-wrap gap-2">{[1, 2, 3, 4].filter(count => Number.isFinite(inputs.leaseMonths) && inputs.leaseMonths >= 1 && inputs.leaseMonths * count <= 360).map(count => <button type="button" key={count} onClick={() => setInputs(p => ({ ...p, months: p.leaseMonths * count }))} className="rounded-full border border-space-border px-3 py-1.5 text-xs hover:border-neon-cyan">{inputs.leaseMonths * count / 12} years</button>)}</div><p className="text-xs leading-relaxed text-text-secondary">Buying: no kilometre limit. You keep the same car after the loan is paid off.</p></div></div>
        {[{ title: "Buy the car", fields: buyFields }, { title: "Lease the car", fields: leaseFields }].map(group => <section key={group.title} className="border-b border-space-border p-6"><h3 className="mb-5 text-sm font-semibold">{group.title}</h3><div className="space-y-4">{group.fields.map(field)}</div></section>)}
        <section className="border-b border-space-border p-6"><h3 className="mb-5 text-sm font-semibold">Key factor</h3>{field(["investmentReturn", "Investment return, after fees & tax", "%/yr", "Annual return on unused starting cash and monthly savings. Starts at zero; not guaranteed."])}<p className="mt-4 text-xs leading-relaxed text-text-secondary">Running-cost inflation: {inputs.runningInflation}%. Mileage and return fees are paid at each lease end. Add missing costs below.</p></section>
        <details className="p-6"><summary className="cursor-pointer text-sm font-semibold">Running costs & lease return fees</summary><div className="mt-5 space-y-4">{advancedFields.map(field)}</div><p className="mt-4 text-xs text-text-secondary">These costs start at zero. Add your estimates for a fuller comparison.</p></details>
      </aside>
      <div className="order-1 min-w-0 space-y-5 lg:order-2" aria-live="polite">
        {error ? <p role="alert" className="rounded-2xl border border-market-down p-6 text-market-down">{error}</p> : result && <>
          <section className="rounded-2xl border border-space-border bg-space-card p-7 sm:p-9" style={{ background: "var(--color-wash)" }}>
            <p className="text-xs font-semibold uppercase tracking-widest text-neon-cyan">Over {inputs.months} months · Your estimates</p>
            <h2 className="mt-4 text-3xl font-semibold leading-tight tracking-tight sm:text-4xl">{Math.abs(difference) < 1 ? "Both paths leave about the same net worth." : <>{difference > 0 ? "Buying" : "Leasing"} leaves you <span className="text-neon-cyan">{money(Math.abs(difference))}</span> ahead.</>}</h2>
            <p className="mt-4 text-sm leading-relaxed text-text-secondary">Car-related net worth after your chosen driving duration: buyer investments plus car value minus debt, compared with lessee investments after return fees.</p>
            <p className="mt-3 text-xs text-text-secondary">Keep one bought car for {inputs.months / 12} years versus {result.leaseCount} lease{result.leaseCount === 1 ? "" : "s"} of {inputs.leaseMonths} months. Repeated leases assume the same payment, upfront costs and return fees; future quotes may differ.</p>
            <div className="mt-7 grid grid-cols-2 gap-4 border-t border-space-border pt-6">{[["Buy · final net worth", result.final.buyWealth], ["Lease · final net worth", result.final.leaseWealth]].map(([label, value]) => <div key={label}><p className="text-xs text-text-secondary">{label}</p><p className="mt-2 break-words font-mono text-2xl sm:text-3xl">{money(Number(value))}</p></div>)}</div>
          </section>
          <section className="rounded-2xl border border-space-border bg-space-card p-6 sm:p-8">
            <h3 className="text-lg font-semibold">How the paths unfold</h3>
            <div role="tablist" aria-label="Car comparison chart" className="mt-4 flex gap-2">{(["wealth", "cash"] as const).map(view => <button key={view} id={`car-tab-${view}`} role="tab" aria-selected={chartView === view} aria-controls="car-chart" onClick={() => setChartView(view)} className={`rounded-full border px-4 py-2 text-xs ${chartView === view ? "border-neon-cyan text-neon-cyan" : "border-space-border text-text-secondary"}`}>{view === "wealth" ? "Net worth" : "Cash outflows"}</button>)}</div>
            <div id="car-chart" role="tabpanel" aria-labelledby={`car-tab-${chartView}`} className="mt-5"><ReactECharts option={chart} style={{ height: 320 }} opts={{ renderer: "svg" }} notMerge /></div>
            <p className="mt-3 text-xs leading-relaxed text-text-secondary">{chartView === "wealth" ? "Values are shown at yearly milestones and the final month. Intermediate car values follow an illustrative straight line from purchase price to your net resale estimate. These are not early-exit outcomes; lease obligations continue until the end." : "Cash outflows include upfront cash in the first period and upfront costs at each new lease and fees at each return. The final period may be shorter than a year. Investment transfers, car sale proceeds and final loan settlement are excluded."}</p>
          </section>
          <section className="grid gap-4 sm:grid-cols-2">{[["Buy · loan payment", result.payment], ["Lease · quoted payment", inputs.lease]].map(([label, value]) => <div key={label} className="rounded-2xl border border-space-border bg-space-card p-6"><p className="text-xs text-text-secondary">{label}</p><p className="mt-3 font-mono text-2xl">{money(Number(value))}<span className="ml-1 text-xs text-text-muted">/ month</span></p><p className="mt-2 text-[11px] text-text-secondary">{label.toString().startsWith("Buy") ? `Loan payments end after ${inputs.loanMonths} months.` : "Upfront costs and return fees are separate."}</p></div>)}</section>
          <section className="rounded-2xl border border-space-border bg-space-card p-6 sm:p-8"><h3 className="text-lg font-semibold">Where the money goes</h3><p className="mt-2 text-xs text-text-secondary">Total amounts over the same {inputs.months}-month period.</p><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[360px] text-sm"><thead><tr className="border-b border-space-border text-xs text-text-secondary"><th className="pb-3 text-left font-medium">Cost breakdown</th><th className="pb-3 text-right font-medium">Buy</th><th className="pb-3 text-right font-medium">Lease</th></tr></thead><tbody>{[
            ["Upfront cash across all leases", inputs.down, result.leaseUpfrontPaid], ["Payments during comparison", result.paid, inputs.lease * inputs.months], ["Running costs", result.buyRunningPaid, result.leaseRunningPaid], ["Mileage & return fees", 0, result.mileageFees + result.totalReturnFees], ["Total cash paid", result.buyCash, result.leaseCash], ["Remaining loan", result.balance, 0], ["Car resale value (credit)", -inputs.resale, 0], ["Total cost after sale / return", result.buyCost, result.leaseCost]
          ].map(([label, buy, lease], i) => <tr key={label} className={`border-b border-space-border last:border-0 ${i === 7 ? "font-semibold text-neon-cyan" : ""}`}><th className="py-3 pr-3 text-left font-normal">{label}</th><td className="py-3 text-right font-mono text-xs">{money(Number(buy))}</td><td className="py-3 pl-3 text-right font-mono text-xs">{money(Number(lease))}</td></tr>)}</tbody></table></div></section>
          <div className="rounded-2xl border border-space-border p-6"><h3 className="flex items-center gap-2 text-sm font-semibold">At the finish line <ArrowRight size={15} /></h3><p className="mt-3 text-sm leading-relaxed text-text-secondary">Buying leaves {money(result.equity)} in car equity before a sale. Leasing leaves no car asset after return. Buy investments: {money(result.final.buyInvestments)}. Lease investments: {money(result.final.leaseInvestments)}. With equal budgets, the cheaper path invests its monthly saving.</p></div>
          <section className="rounded-2xl border border-space-border bg-space-card p-6 sm:p-8"><h3 className="text-lg font-semibold">What would change the result?</h3><p className="mt-2 text-xs text-text-secondary">Final net-worth equality, changing one assumption at a time.</p><div className="mt-5 grid gap-5 sm:grid-cols-2">{[["lease", "Break-even monthly lease payment", thresholds?.lease], ["resale", "Break-even net resale value", thresholds?.resale]].map(([key, label, value]) => <div key={key}><p className="text-xs text-text-secondary">{label}</p><p className="mt-2 font-mono text-xl">{value == null ? "No crossing in range" : money(Number(value))}</p><p className="mt-2 text-xs leading-relaxed text-text-secondary">{key === "lease" ? "Lower payments favour leasing; higher payments favour buying. Search: 0–100,000 per month." : "Higher resale values favour buying; lower values favour leasing. Search: 0–100 million."}</p>{value != null && <button className="mt-3 text-xs font-semibold text-neon-cyan underline underline-offset-4" onClick={() => setInputs(p => ({ ...p, [String(key)]: Number(value) }))}>Apply break-even value</button>}</div>)}</div></section>
          <details className="rounded-2xl border border-space-border bg-space-card p-6"><summary className="cursor-pointer text-sm font-semibold">How the wealth calculation works</summary><div className="mt-4 space-y-3 text-xs leading-relaxed text-text-secondary"><p>Both start with {money(result.startingCash)}. After upfront costs, the buyer invests {money(result.buyInitialInvestments)} and the lessee invests {money(result.leaseInitialInvestments)}.</p><p>Each month, both have the same budget: the higher of the two paths’ actual costs. Existing investments compound at the equivalent monthly rate, then the cheaper path invests its saving at month-end. Lease return fees or a new lease’s upfront costs can make leasing the more expensive path in those months.</p><p>Buy net worth = net car value + investments − loan balance. Lease net worth = investments. Loan interest paid: {money(result.interestPaid)}; principal repaid: {money(result.principalPaid)}. Negative equity and negative net worth are preserved.</p><p>At zero investment return, the net-worth advantage equals the total-cost advantage. With investment returns, they may differ. These balances cover the car decision only.</p></div></details>
          <details className="rounded-2xl border border-space-border bg-space-card p-6"><summary className="cursor-pointer text-sm font-semibold">Annual breakdown & export</summary><p className="mt-3 text-xs text-text-secondary">Yearly periods plus any shorter final period. CSV includes all assumptions and monthly calculations.</p><button onClick={downloadCsv} className="mt-4 rounded-full border border-space-border px-4 py-2 text-xs font-semibold hover:bg-space-void">Download scenario CSV</button><label htmlFor="car-scenario-csv" className="mt-4 block text-xs text-text-secondary">Or copy your assumptions and monthly results</label><textarea id="car-scenario-csv" readOnly value={carScenarioCsv(inputs, currency)} rows={5} onFocus={e => e.currentTarget.select()} className="mt-2 w-full rounded-lg border border-space-border bg-space-void p-3 font-mono text-[11px]" /><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[780px] text-xs"><thead><tr className="border-b border-space-border">{["Months", "Loan left", "Interest", "Principal", "Buy net worth", "Lease net worth", "Buy cash paid", "Lease cash paid"].map(label => <th key={label} className="px-2 py-3 text-right first:text-left font-medium text-text-secondary">{label}</th>)}</tr></thead><tbody>{result.periods.map(p => <tr key={p.month} className="border-b border-space-border"><th className="px-2 py-3 text-left font-normal">{p.startMonth}–{p.month}</th>{[p.balance, p.interest, p.principal, p.buyWealth, p.leaseWealth, p.buyCashOutflow, p.leaseCashOutflow].map((v, i) => <td key={i} className="px-2 py-3 text-right font-mono">{money(v)}</td>)}</tr>)}</tbody></table></div></details>
        </>}
        <details className="rounded-2xl border border-space-border p-6"><summary className="cursor-pointer text-sm font-semibold">How this comparison works</summary><div className="mt-4 space-y-3 text-xs leading-relaxed text-text-secondary"><p>Buy cost = down payment + loan payments + running costs + remaining debt − net resale value. Lease cost = upfront costs + all monthly payments + running costs + excess mileage + return fees. Loan principal is not charged twice: the remaining balance is settled from sale proceeds.</p><p>Use tax-inclusive quotes. Refundable deposits are excluded. Buying keeps the same car for the full duration. Leasing repeats identical contracts, with upfront costs at each start and mileage and return fees at each end. Driving duration must cover complete lease terms. Early termination, lease buyouts, replacement purchases and business tax deductions are excluded. Running costs can inflate; other quoted costs stay fixed. Investment returns use your after-fee, after-tax assumption. Resale value is an estimate, not a forecast. Annual kilometres and allowances apply only to leasing. Buying has no mileage limit or excess-kilometre fee; enter resale and running-cost estimates that reflect your own use. No assumptions are saved or sent. See the <a className="underline underline-offset-2" href="https://www.canada.ca/en/financial-consumer-agency/services/loans/financing-car/financing-options.html" target="_blank" rel="noopener noreferrer">FCAC car financing guide</a> for buying and leasing considerations.</p></div></details>
      </div>
    </div>
  </div>;
}
